const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const {server,until,mapFixtures}=require('./helpers.cjs');
const elements=[
 {type:'node',id:11,lat:53.5511,lon:9.9937,tags:{name:'Pizza Max',cuisine:'pizza',amenity:'restaurant',opening_hours:'24/7'}},
 {type:'node',id:12,lat:53.552,lon:9.998,tags:{name:'Pizza Café',cuisine:'pizza',amenity:'cafe',opening_hours:'off'}},
 {type:'node',id:13,lat:53.553,lon:9.993,tags:{name:'Pizza Imbiss',cuisine:'pizza',amenity:'fast_food'}},
 {type:'node',id:14,lat:53.554,lon:9.992,tags:{name:'Pizza Truck',cuisine:'pizza',amenity:'food_truck',opening_hours:'24/7'}},
 {type:'node',id:15,lat:53.554,lon:9.994,tags:{name:'Pizzaautomat',vending:'pizza',amenity:'vending_machine',opening_hours:'24/7'}},
 {type:'node',id:16,lat:53.555,lon:9.996,tags:{name:'Pizza Bar',cuisine:'pizza',amenity:'pub',opening_hours:'24/7'}},
 {type:'node',id:17,lat:53.554,lon:9.997,tags:{name:'Trattoria Roma',cuisine:'italian',amenity:'restaurant',opening_hours:'24/7'}}
];
const feature=(id,name,food=true)=>({geometry:{coordinates:[9.9937,53.5511]},properties:{name,osm_type:'N',osm_id:id,osm_key:food?'amenity':'place',osm_value:food?'restaurant':'city',street:'Hamburger Straße',housenumber:'42',postcode:'22926',city:'Ahrensburg',countrycode:'DE',state:'Schleswig-Holstein'}});
(async()=>{const {server:s,url}=await server(),browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:393,height:851}}),page=await ctx.newPage(),errors=[];let primary=0,secondary=0,geocalls=0;fs.mkdirSync('test-results',{recursive:true});page.on('pageerror',e=>errors.push(e.message));await mapFixtures(page);
 await page.route('**/overpass-api.de/**',r=>{primary++;return r.fulfill({status:503,body:'Unavailable'});});
 await page.route('**/overpass.private.coffee/**',r=>{secondary++;const query=new URLSearchParams(r.request().postData()).get('data');const exact=/;node\(11\);/.test(query);return r.fulfill({json:{elements:exact?[{...elements[0],tags:{...elements[0].tags,phone:'+49 4102 12345',website:'https://example.org/pizzeria','website:menu':'https://example.org/menu',delivery:'yes',takeaway:'yes',wheelchair:'yes','diet:vegan':'yes',outdoor_seating:'yes'}}]:elements}});});
 await page.route('**/photon.komoot.io/**',r=>{geocalls++;const q=new URL(r.request().url()).searchParams.get('q');return r.fulfill({json:{features:q==='Max Ahrensburg'?[feature(111,'Pizza Max Süd'),feature(11,'Pizza Max'),feature(99,'Ahrensburg',false)]:[feature(11,'Pizza Max')]}});});
 try{await page.goto(url);await until(page,()=>PizzaScan.ready);await page.locator('#welcome-start').click();await until(page,()=>PizzaScan.diagnostics().places===7&&!PizzaScan.diagnostics().mapLoading);assert.equal(primary,1);assert.equal(secondary,1);assert.equal(await page.locator('#map .emoji-marker').count(),7);for(const emoji of ['🍕','☕','🍔','🚚','🤖','🍽️'])assert.ok((await page.locator('#map .emoji-marker').allTextContents()).join('').includes(emoji));assert.equal(await page.locator('#map-notice').isVisible(),false);
 const hours=await page.evaluate(()=>{const p={lat:53.55,lng:10,country:'de',state:'Hamburg'};const calc=(rule,date)=>PizzaHours.status({...p,openingHours:rule},new Date(date)).state;return {open:calc('Mo-Fr 10:00-22:00','2026-09-09T10:00:00Z'),closed:calc('Mo-Fr 10:00-22:00','2026-09-09T21:00:00Z'),overnight:calc('Fr 18:00-02:00','2026-09-11T23:00:00Z'),after:calc('Fr 18:00-02:00','2026-09-12T01:00:00Z'),holiday:calc('Mo-Su 10:00-22:00; PH off','2026-12-25T12:00:00Z'),invalid:calc('definitely not hours','2026-09-09T12:00:00Z'),missing:calc('','2026-09-09T12:00:00Z'),winter:calc('Mo-Su 10:00-11:00','2026-12-02T09:30:00Z'),summer:calc('Mo-Su 10:00-11:00','2026-09-02T08:30:00Z'),foreign:PizzaHours.status({lat:40.71,lng:-74,openingHours:'Mo-Su 10:00-11:00'},new Date('2026-09-09T14:30:00Z')).state,week:PizzaHours.week({...p,openingHours:'24/7'}).map(x=>x.hours)};});assert.deepEqual({...hours,week:undefined},{open:'open',closed:'closed',overnight:'open',after:'closed',holiday:'closed',invalid:'unknown',missing:'unknown',winter:'open',summer:'open',foreign:'open',week:undefined});assert.equal(hours.week.length,7);assert.ok(hours.week.every(x=>x==='00:00–24:00'));
 await page.screenshot({path:'test-results/map-emoji-mobile.png',fullPage:true});
 const mapCenterBefore=await page.evaluate(()=>map.getCenter());await page.locator('#map-fullscreen').click();await until(page,()=>PizzaScan.diagnostics().mapFullscreen&&document.getElementById('map').getBoundingClientRect().height===innerHeight);assert.equal(await page.locator('#fs-back').isVisible(),true);const box=await page.locator('#map').boundingBox();assert.equal(box.x,0);assert.equal(box.y,0);assert.equal(box.width,393);await page.screenshot({path:'test-results/map-fullscreen-mobile.png'});
 await page.locator('#fs-search').click();await page.locator('#search').fill('Pizza Max');await until(page,()=>document.querySelector('#search-results .search-result'));assert.equal(geocalls,0);await page.locator('#search').fill('');await page.locator('#fs-search').click();await page.locator('#fs-filter').click();assert.equal(await page.locator('#filters-save').isVisible(),true);assert.equal(await page.evaluate(()=>PizzaScan.back()),true);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().mapFullscreen),true,'Back first closes the filter sheet');await page.locator('#fs-back').click();await until(page,()=>!PizzaScan.diagnostics().mapFullscreen);const centerAfter=await page.evaluate(()=>map.getCenter());assert.ok(Math.abs(centerAfter.lat-mapCenterBefore.lat)<.00001&&Math.abs(centerAfter.lng-mapCenterBefore.lng)<.00001,'Fullscreen retains search center');
 await page.locator('#map-fullscreen').click();await page.setViewportSize({width:851,height:393});await until(page,()=>document.getElementById('map').getBoundingClientRect().height===393);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/map-fullscreen-landscape.png'});await page.keyboard.press('Escape');await until(page,()=>!PizzaScan.diagnostics().mapFullscreen);await page.setViewportSize({width:393,height:851});

 await page.locator('#search').fill('pizza max');await until(page,()=>document.querySelector('#search-results .search-result'));assert.equal(geocalls,0,'Typing searches local data only');assert.match(await page.locator('#search-results').innerText(),/Pizza Max/);await page.locator('#search-results .search-result').first().click();await until(page,()=>document.getElementById('sheet-body').textContent.includes('Hamburger Straße 42')&&!document.querySelector('.detail-loading'));assert.equal(await page.locator('.hours-table tr').count(),7);assert.ok(await page.getByRole('button',{name:'☎ Anrufen'}).isVisible());assert.ok(await page.getByRole('button',{name:'📋 Speisekarte'}).isVisible());assert.match(await page.locator('.venue-facts').innerText(),/Rollstuhl[\s\S]*Ja/);await page.screenshot({path:'test-results/place-details-mobile.png',fullPage:true});await page.locator('#sheet-close').click();
 await page.locator('#search').fill('Max Ahrensburg');await page.locator('#search-submit').click();await until(page,()=>document.getElementById('search-status').textContent.includes('wähle'));assert.equal(await page.locator('#search-results .search-result').count(),3,'Local exact venue plus distinct remote choices');await page.locator('#search').fill('');await until(page,()=>document.getElementById('search-results').hidden);
 await until(page,()=>!PizzaScan.diagnostics().mapLoading);await page.locator('#open-filter').click();assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().visiblePlaces),5);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().markerCount),5);await page.locator('#filter-open').click();await page.locator('#filter-unknown').check();await page.locator('#filter-italian').uncheck();await page.locator('#filter-auto').uncheck();await page.locator('#filters-save').click();assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().visiblePlaces),5);
 await page.locator('#filter-open').click();for(const type of ['pizzeria','fast_food','food_truck','other','cafe'])await page.locator('input[name=place-type][value='+type+']').uncheck();await page.locator('#filters-save').click();assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().markerCount),1);assert.match(await page.locator('#places').innerText(),/Pizzaautomat/);await page.reload();await until(page,()=>PizzaScan.ready);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().mapConfig.types.join()),'vending_pizza');assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().markerCount),1);
 await page.locator('#settings-open').click();assert.equal(await page.locator('#community-open').count(),0);assert.equal(await page.locator('#filter-only-open').isChecked(),true);await page.screenshot({path:'test-results/map-settings-mobile.png'});await page.locator('#sheet-close').click();const before=secondary;await page.locator('#map-refresh').click();await until(page,()=>!PizzaScan.diagnostics().mapLoading);assert.ok(secondary>before,'Explicit search refreshes unchanged center');const calls=secondary;await page.locator('#map').hover();await page.mouse.move(180,520);await page.mouse.down();await page.mouse.move(220,550,{steps:8});await page.mouse.up();await page.waitForTimeout(1200);assert.equal(secondary,calls,'Automatic search can be disabled');await page.locator('#map-fullscreen').click();await until(page,()=>PizzaScan.diagnostics().mapFullscreen);await page.locator('#map .emoji-marker').first().click();await page.locator('.venue-popup [data-action=place]').click();await until(page,()=>!document.querySelector('.detail-loading'));await page.locator('#sheet-body [data-action=choose]').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().mapFullscreen),false);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().view),'photo');assert.equal(await page.evaluate(()=>scrollY),0,'Choosing a photo from fullscreen restores normal navigation');assert.deepEqual(errors,[]);
 // A fresh install with unwritable storage must still initialize and show remote results.
 const quota=await browser.newContext({viewport:{width:393,height:851}});await quota.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});const qpage=await quota.newPage();await mapFixtures(qpage);await qpage.goto(url);await until(qpage,()=>PizzaScan.ready);await qpage.locator('#welcome-start').click();await until(qpage,()=>PizzaScan.diagnostics().places===2&&!PizzaScan.diagnostics().mapLoading);assert.equal(await qpage.evaluate(()=>PizzaScan.diagnostics().mapError),'');await quota.close();
 console.log('PASS clean first start, provider fallback, six emoji types, fullscreen portrait/landscape/search/filter/back/center retention, precise search choices, exact address enrichment, full detail fields, real opening-hours parser/timezones/holidays/overnight, strict filters, persistence, manual refresh, disabled auto-search, storage quota');
 }catch(e){await page.screenshot({path:'test-results/map-failure.png'}).catch(()=>{});throw e;}finally{await browser.close();s.close();}})().catch(e=>{console.error(e);process.exit(1)});
