const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const {server,until,mapFixtures}=require('./helpers.cjs');
(async()=>{const {server:s,url}=await server(),browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:393,height:820},permissions:['clipboard-read','clipboard-write'],geolocation:{latitude:53.5511,longitude:9.9937}});const page=await ctx.newPage(),errors=[];fs.mkdirSync('test-results',{recursive:true});page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});await mapFixtures(page);page.on('dialog',d=>d.accept());
 // UI fixture only; tests/model-integration.cjs exercises real model weights separately.
 await ctx.addInitScript(()=>{window.Worker=class{postMessage(m){setTimeout(()=>{const scores=PizzaAnalysis.results(Array.from({length:100},(_,i)=>i%4===2?3:0));this.onmessage({data:{type:'result',scores,overall:PizzaAnalysis.overall(scores),method:PizzaAnalysis.method,createdAt:new Date().toISOString()}})},20)}terminate(){}};});
 const events=[];await page.routeWebSocket(/wss:\/\/(relay\.damus\.io|nos\.lol)\//,ws=>{ws.onMessage(raw=>{const m=JSON.parse(raw);if(m[0]==='EVENT'){events.push(m[1]);ws.send(JSON.stringify(['OK',m[1].id,true,'saved by local test relay']));}if(m[0]==='REQ'){for(const e of events.filter(e=>m[2].kinds.includes(e.kind)))ws.send(JSON.stringify(['EVENT',m[1],e]));ws.send(JSON.stringify(['EOSE',m[1]]));}});});
 try{await page.goto(url);await until(page,()=>PizzaScan.ready);await page.locator('#welcome-start').click();await until(page,()=>PizzaScan.diagnostics().places===2);assert.equal(await page.locator('#places img').count(),0);await page.locator('#places [data-action=save]').first().click();await page.screenshot({path:'test-results/map-mobile.png'});await page.locator('#places [data-action=choose]').first().click();
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=300;const x=c.getContext('2d');x.fillStyle='#f8cb78';x.fillRect(0,0,400,300);x.fillStyle='#d94e26';x.beginPath();x.arc(200,150,115,0,Math.PI*2);x.fill();return c.toDataURL().split(',')[1];});await page.locator('#photo-input').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await until(page,()=>!document.getElementById('analyze').disabled);await page.locator('#analyze').click();assert.equal(await page.locator('#confirm-model-download').count(),1);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().busy),false);await page.locator('#confirm-model-download').click();await until(page,()=>PizzaScan.diagnostics().reports===1);assert.equal(await page.locator('#criteria-panel .metric').count(),25);await page.locator('#experts-tab').click();assert.equal(await page.locator('#expert-select option').count(),100);await page.locator('#expert-select').selectOption('100');assert.equal(await page.locator('#expert-detail tbody tr').count(),25);await page.screenshot({path:'test-results/profile-mobile.png'});await page.locator('#criteria-tab').click();assert.equal(await page.locator('#review-draft').isDisabled(),true);
 await page.locator('#own-rating').fill('7.8');await page.locator('#own-notes').fill('Der Rand hat mir gut gefallen.');await page.locator('#visited').check();await page.locator('#save-own').click();await until(page,()=>!document.getElementById('review-draft').disabled);await page.locator('#review-draft').click();assert.match(await page.locator('#draft-text').inputValue(),/7,8/);assert.match(await page.locator('#sheet-body').innerText(),/4 von 5 Sternen/);await page.locator('#draft-text').fill('Mein bearbeiteter Rezensionstext.');await page.locator('#copy-draft').click();await until(page,()=>document.getElementById('toast').textContent==='Rezension kopiert');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'Mein bearbeiteter Rezensionstext.');await page.screenshot({path:'test-results/review-mobile.png'});
 await page.reload();await until(page,()=>PizzaScan.ready);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().reports),1);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().saved),1);await page.locator('#nav-photo').click();await page.locator('[data-action=report]').first().click();await page.locator('#publish-review').click();assert.equal(await page.locator('#confirm-publish').isDisabled(),true);assert.equal(events.length,0,'No automatic public events');await page.locator('#public-consent').check();await page.locator('#confirm-publish').click();await until(page,()=>document.getElementById('load-community'));assert.ok(events.length>=1,'Signed event sent only to mocked relay');await page.locator('#load-community').click();await until(page,()=>document.getElementById('community-status').textContent.includes('verifizierte'));assert.equal(await page.locator('#community-feed [data-action=public-detail]').count(),1);
 await page.locator('[data-action=public-detail]').click();await page.locator('[data-action=comments]').click();await until(page,()=>document.getElementById('send-comment'));await page.locator('#comment-text').fill('Testkommentar, nur lokaler Relay.');await page.locator('#send-comment').click();await until(page,()=>document.getElementById('comments').textContent.includes('Testkommentar, nur lokaler Relay.'));assert.ok(events.some(e=>e.kind===1));
 await page.evaluate(()=>PizzaScan.back());await page.locator('#settings-open').click();await page.locator('input[value=siglip]').check();await page.locator('#dark-mode').check();await page.locator('#settings-save').click();await page.reload();await until(page,()=>PizzaScan.ready);assert.equal(await page.evaluate(()=>PizzaScan.diagnostics().model),'siglip');assert.equal(await page.locator('body').evaluate(b=>b.classList.contains('dark')),true);await page.locator('#settings-open').click();await page.screenshot({path:'test-results/settings-mobile.png'});await page.setViewportSize({width:740,height:393});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS map, photo, 25 criteria, 100 profiles, personal score, review draft, persistence, explicit community consent, real signatures, relay ACK, feed, comment, settings, dark, landscape');
 }catch(e){await page.screenshot({path:'test-results/failure.png'}).catch(()=>{});throw e;}finally{await browser.close();s.close();}})().catch(e=>{console.error(e);process.exit(1)});
