import {generateSecretKey,finalizeEvent,verifyEvent,getPublicKey} from 'nostr-tools/pure';
const RELAYS=['wss://relay.damus.io','wss://nos.lol'];
const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
let secret;
export async function identity(bridge){if(secret)return getPublicKey(secret);let stored=await bridge('secretGet');if(!stored){stored=hex(generateSecretKey());await bridge('secretPut',{text:stored});}if(!/^[0-9a-f]{64}$/.test(stored))throw Error('Community-Identität beschädigt');secret=Uint8Array.from(stored.match(/../g),s=>parseInt(s,16));return getPublicKey(secret);}
export function decode(event){try{if(event.kind!==30078||event.content.length>48000||!event.tags.some(t=>t[0]==='t'&&t[1]==='pizzascan')||!verifyEvent(event))return null;const r=JSON.parse(event.content);if(r.schema!=='pizzascan-review-2'||!r.id||typeof r.id!=='string'||r.id.length>80||!event.tags.some(t=>t[0]==='d'&&t[1]===r.id))return null;
 const C=globalThis.PizzaCore,A=globalThis.PizzaAnalysis;const place=C.place(r.place),scores=A.validateScores(r.scores);A.stars(r.own);if(!A.models.some(m=>m.id===r.model)||r.method!==A.method)return null;
 return {id:event.id,sourceId:r.id,pubkey:event.pubkey,createdAt:new Date(event.created_at*1000).toISOString(),name:String(r.name||'Pizza-Fan').slice(0,40),place,scores,own:r.own,notes:String(r.notes||'').slice(0,1500),model:r.model,method:r.method,photo:typeof r.photo==='string'&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(r.photo)&&r.photo.length<35000?r.photo:'',overall:A.overall(scores),community:true};
 }catch{return null;}}
function socketRead(url,filter){return new Promise((resolve,reject)=>{const ws=new WebSocket(url),events=[],id=crypto.randomUUID();let ended=false;const timer=setTimeout(()=>finish(Error('Relay antwortet nicht')),12000);function finish(error){if(ended)return;ended=true;clearTimeout(timer);if(ws.readyState===1)ws.send(JSON.stringify(['CLOSE',id]));ws.close();error?reject(error):resolve(events);}
 ws.onopen=()=>ws.send(JSON.stringify(['REQ',id,filter]));ws.onerror=()=>finish(Error('Relay nicht erreichbar'));ws.onclose=()=>{if(!ended)finish(Error('Relay hat die Verbindung beendet'));};ws.onmessage=e=>{if(typeof e.data!=='string'||e.data.length>60000)return;try{const m=JSON.parse(e.data);if(m[0]==='EVENT'&&m[1]===id&&events.length<100)events.push(m[2]);if(m[0]==='EOSE'&&m[1]===id)finish();if(m[0]==='CLOSED'&&m[1]===id)finish(Error('Relay hat die Abfrage abgelehnt'));}catch{}};
 });}
async function query(filter){const rs=await Promise.allSettled(RELAYS.map(r=>socketRead(r,filter)));const good=rs.filter(r=>r.status==='fulfilled');if(!good.length)throw Error('Die kostenlosen Community-Relays sind gerade nicht erreichbar. Bitte später erneut versuchen.');return {events:[...new Map(good.flatMap(r=>r.value).map(e=>[e.id,e])).values()],connected:good.length};}
export async function feed(){const r=await query({kinds:[30078],'#t':['pizzascan'],limit:60});let items=r.events.map(decode).filter(Boolean);if(items.length){try{const deleted=await query({kinds:[5],'#e':items.map(x=>x.id),limit:100});items=items.filter(item=>!deleted.events.some(e=>e.kind===5&&e.pubkey===item.pubkey&&e.content.length<2000&&e.tags.some(t=>t[0]==='e'&&t[1]===item.id)&&verifyEvent(e)));}catch{/* Relay deletion support is best effort; UI warns that copies may remain. */}}return {items:items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),connected:r.connected};}
function send(url,event){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let done=false;const timer=setTimeout(()=>finish(Error('Keine Bestätigung vom Relay')),12000);function finish(e){if(done)return;done=true;clearTimeout(timer);ws.close();e?reject(e):resolve(url);}ws.onopen=()=>ws.send(JSON.stringify(['EVENT',event]));ws.onerror=()=>finish(Error('Relay nicht erreichbar'));ws.onclose=()=>{if(!done)finish(Error('Verbindung beendet'));};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m[0]==='OK'&&m[1]===event.id)finish(m[2]?null:Error(String(m[3]||'Abgelehnt')));}catch{}};});}
async function publish(template){if(!secret)throw Error('Community-Identität fehlt');const event=finalizeEvent({...template,created_at:Math.floor(Date.now()/1000)},secret);const acks=await Promise.allSettled(RELAYS.map(r=>send(r,event)));const good=acks.filter(r=>r.status==='fulfilled');if(!good.length)throw Error('Kein Relay hat den Beitrag bestätigt. Es kann trotzdem eine Kopie vorliegen; bitte später nachsehen.');return {event,confirmed:good.length};}
export async function post(r,thumb){globalThis.PizzaAnalysis.validateScores(r.scores);globalThis.PizzaAnalysis.stars(r.own);if(!r.place)throw Error('Pizzeria zuordnen');const content=JSON.stringify({schema:'pizzascan-review-2',id:r.id,place:{placeId:r.place.placeId,name:r.place.name,lat:r.place.lat,lng:r.place.lng,address:r.place.address},photo:thumb,scores:r.scores,own:r.own,notes:r.notes,model:r.model,method:r.method});if(content.length>48000)throw Error('Beitrag zu groß');return publish({kind:30078,tags:[['d',r.id],['t','pizzascan']],content});}
export async function comments(id){const r=await query({kinds:[1],'#e':[id],'#t':['pizzascan'],limit:40});return r.events.filter(e=>e.kind===1&&e.content.length<=1500&&e.tags.some(t=>t[0]==='e'&&t[1]===id)&&verifyEvent(e)).sort((a,b)=>a.created_at-b.created_at).map(e=>({id:e.id,pubkey:e.pubkey,text:e.content}));}
export function comment(id,text){if(!text.trim()||text.length>1500)throw Error('Kommentar: 1–1500 Zeichen');return publish({kind:1,tags:[['e',id,'','root'],['t','pizzascan']],content:text.trim()});}
export function remove(id,sourceId){return publish({kind:5,tags:[['e',id],['a','30078:'+getPublicKey(secret)+':'+sourceId]],content:'Gelöscht durch den Autor'});}
