import OpeningHours from 'opening_hours';
import tzlookup from 'tz-lookup';
const parsed=new Map();
export function timezone(place){try{return tzlookup(place.lat,place.lng);}catch{return null;}}
export function wallDate(date,zone){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const p=Object.fromEntries(parts.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));return new Date(p.year,p.month-1,p.day,p.hour,p.minute,p.second);}
function evaluator(place){const country=place.country||'',state=place.state||'';if(/\b(PH|SH)\b/.test(place.openingHours)&&(!country||!state))throw Error('Für Feiertagsregeln fehlen Land oder Region.');if(/sunrise|sunset|dawn|dusk/.test(place.openingHours))throw Error('Sonnenzeit-Regel: Öffnungsstatus bitte vor Ort prüfen.');const key=[place.openingHours,country,state].join('|');if(parsed.has(key))return parsed.get(key);const oh=new OpeningHours(place.openingHours,{lat:place.lat,lon:place.lng,address:{country_code:country.toLowerCase(),state}},{mode:0,locale:'de'});if(parsed.size>500)parsed.clear();parsed.set(key,oh);return oh;}
const clock=d=>d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
export function status(place,now=new Date()){
 const zone=timezone(place);if(!place.openingHours)return {state:'unknown',label:'Zeiten unbekannt',zone,note:'Keine Öffnungszeiten in den Quelldaten.'};
 try{if(!zone)throw Error('Zeitzone nicht bestimmbar');const date=wallDate(now,zone),oh=evaluator(place),unknown=oh.getUnknown(date);if(unknown)return {state:'unknown',label:'Öffnung unklar',zone,note:oh.getComment(date)||'Keine eindeutige Öffnungszeit.'};const open=oh.getState(date),limit=new Date(date.getTime()+8*86400000),next=oh.getNextChange(date,limit);let change='';if(next){change=(open?'Schließt ':'Öffnet ')+(next.toDateString()===date.toDateString()?'um ':next.toLocaleDateString('de-DE',{weekday:'short',day:'numeric',month:'short'})+' um ')+clock(next);}return {state:open?'open':'closed',label:open?'Jetzt geöffnet':'Jetzt geschlossen',zone,note:change||(place.openingHours==='24/7'?'Rund um die Uhr':oh.getComment(date)||'Laut hinterlegten Öffnungszeiten')};}
 catch(e){return {state:'unknown',label:'Zeiten nicht auswertbar',zone,note:String(e.message||e).slice(0,180)};}
}
export function week(place,now=new Date()){
 try{const zone=timezone(place);if(!zone||!place.openingHours)return [];const oh=evaluator(place),date=wallDate(now,zone);date.setHours(0,0,0,0);return Array.from({length:7},(_,i)=>{const start=new Date(date);start.setDate(start.getDate()+i);const end=new Date(start);end.setDate(end.getDate()+1);const intervals=oh.getOpenIntervals(start,end);return {day:start.toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'short'}),hours:intervals.length?intervals.map(x=>clock(x[0])+'–'+(x[1].getTime()===end.getTime()?'24:00':clock(x[1]))+(x[2]?' (unklar)':'')).join(', '):'Geschlossen'};});}catch{return [];}}
