/* PizzaScan Build 39 runtime finalizer.
 * The proven Build 38/WebSim discovery/query/filter logic stays untouched.
 * This layer removes one provider, adds durable visited-place UX and a review
 * portal hub around the existing draft + Mangrove publishing implementation.
 */
(function(root,factory){
 const api=factory();
 if(typeof module==='object'&&module.exports)module.exports=api;
 else{root.PizzaBuild39=api;api.install(root);}
})(globalThis,function(){
'use strict';
const BLOCKED_PROVIDER_HOST='maps.'+'mail.ru';
const MANUAL_EVENT_PREFIX='manual:';
function hostOf(v){try{return new URL(String(v)).hostname.toLowerCase();}catch{return '';}}
function blockedProvider(v){return hostOf(v)===BLOCKED_PROVIDER_HOST;}
function stripProviderArray(a){if(!Array.isArray(a))return a;for(let i=a.length-1;i>=0;i--)if(blockedProvider(a[i]))a.splice(i,1);return a;}
function latestEvent(r){return [...(r?.events||[])].filter(e=>Number.isFinite(Number(e?.rating))).sort((a,b)=>Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0))[0]||null;}
function mangroveSubject(p){return p?.name&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))?`geo:${Number(p.lat)},${Number(p.lng)}?q=${encodeURIComponent(String(p.name).slice(0,200))}&u=30`:'';}
function portalUrls(p){const name=String(p?.name||'').trim(),addr=String(p?.address||'').trim(),pos=Number.isFinite(Number(p?.lat))&&Number.isFinite(Number(p?.lng))?`${Number(p.lat)},${Number(p.lng)}`:'',q=[name,addr||pos].filter(Boolean).join(' '),sub=mangroveSubject(p);return{google:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,yelp:`https://www.yelp.com/search?find_desc=${encodeURIComponent(name||'restaurant')}&find_loc=${encodeURIComponent(addr||pos)}`,tripadvisor:`https://www.tripadvisor.com/Search?q=${encodeURIComponent(q)}`,mangrove:`https://mangrove.reviews/search?sub=${encodeURIComponent(sub)}`};}
function validArchiveObject(d,h){return !!d&&d.format===h?.ARCHIVE_FORMAT&&Number(d.version)===Number(h?.ARCHIVE_VERSION)&&Array.isArray(d.visits)&&d.visits.length<=100000;}
function install(root){
 if(typeof root.document==='undefined')return false;
 stripProviderArray(root.PizzaSmartDiscovery?.PROVIDERS);stripProviderArray(root.PizzaSmartDiscovery?.RECOVERY_PROVIDERS);stripProviderArray(root.PizzaNativeOverpass?.ENDPOINTS);
 if(root.PizzaScanSmartDiscovery?.providers)root.PizzaScanSmartDiscovery.providers=stripProviderArray([...root.PizzaScanSmartDiscovery.providers]);
 if(root.PizzaScanNativeOverpass?.endpoints)root.PizzaScanNativeOverpass.endpoints=stripProviderArray([...root.PizzaScanNativeOverpass.endpoints]);
 try{if(typeof placeService!=='undefined'&&typeof placeService.json==='function'&&!placeService.json.__build39ProviderPolicy){const inner=placeService.json.bind(placeService),wrapped=async(url,...args)=>{if(blockedProvider(url))throw Error('Diese Kartenquelle ist in PizzaScan deaktiviert.');return inner(url,...args);};wrapped.__build39ProviderPolicy=true;placeService.json=wrapped;}}catch{}
 try{if(typeof mapSource==='string'&&mapSource.includes(BLOCKED_PROVIDER_HOST))mapSource=mapSource.split(' + ').filter(x=>!x.includes(BLOCKED_PROVIDER_HOST)).join(' + ');}catch{}
 const H=root.PizzaPlaceHistory,R=root.PizzaPlaceHistoryRuntime;let visits=new Map();
 const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error||Error('Speicherzugriff fehlgeschlagen.'));});
 const database=()=>R?.db?.();
 async function getVisit(id){const d=await database();return d?req(d.transaction(H.VISIT_STORE,'readonly').objectStore(H.VISIT_STORE).get(id)):null;}
 async function allVisits(){const d=await database();return d?req(d.transaction(H.VISIT_STORE,'readonly').objectStore(H.VISIT_STORE).getAll()):[];}
 function putMany(d,store,rows){return new Promise((ok,no)=>{const tx=d.transaction(store,'readwrite'),os=tx.objectStore(store);for(const row of rows||[])os.put(row);tx.oncomplete=ok;tx.onerror=()=>no(tx.error||Error('Speichern fehlgeschlagen.'));tx.onabort=()=>no(tx.error||Error('Speichern abgebrochen.'));});}
 function updateCount(){const b=root.document.getElementById('visited-library-open');if(b)b.innerHTML=`📍 Besucht & bewertet <span class="badge">${visits.size}</span>`;}
 async function refreshVisits(redraw=false){if(!H||!R)return[];const rows=await allVisits();visits=new Map(rows.map(r=>[r.placeId,r]));R.visitedIds?.clear?.();for(const r of rows)R.visitedIds?.add?.(r.placeId);updateCount();if(redraw&&typeof renderPlaces==='function')renderPlaces();return rows;}
 async function saveVisit(place,rating,notes=''){if(!H||!R)throw Error('Besuchsarchiv ist noch nicht verfügbar.');const n=Number(String(rating).replace(',','.'));if(!Number.isFinite(n)||n<.1||n>10)throw Error('Bitte eine Bewertung zwischen 0,1 und 10,0 eingeben.');const p=H.cleanPlace(place),d=await database(),old=await getVisit(p.placeId),now=new Date().toISOString(),next=H.mergeVisitRecords(old,{placeId:p.placeId,place:p,updatedAt:now,events:[{id:MANUAL_EVENT_PREFIX+p.placeId,rating:Math.round(n*10)/10,notes:String(notes||'').trim().slice(0,4000),source:'manual',updatedAt:now}]});await putMany(d,H.VISIT_STORE,[next]);await putMany(d,H.PLACE_STORE,[p]);visits.set(p.placeId,next);R.visitedIds?.add?.(p.placeId);try{if(typeof mapPool!=='undefined')mapPool=PlaceData.merge(mapPool,[p]);}catch{}updateCount();if(typeof renderPlaces==='function')renderPlaces();return next;}
 async function importRows(rows){const d=await database(),merged=[];for(const row of rows||[]){const old=await getVisit(row.placeId),next=H.mergeVisitRecords(old,row);merged.push(next);}await putMany(d,H.VISIT_STORE,merged);await putMany(d,H.PLACE_STORE,merged.map(x=>x.place));try{if(typeof mapPool!=='undefined')mapPool=PlaceData.merge(mapPool,merged.map(x=>x.place));}catch{}await refreshVisits(true);return merged.length;}
 async function exportJson(){const rows=await allVisits(),name='PizzaScan-Besuchsarchiv-'+new Date().toISOString().slice(0,10)+'.json';await bridge('save',{name,text:JSON.stringify(H.archiveObject(rows),null,2)});toast(`${rows.length} besuchte und bewertete Orte gesichert.`);}
 async function exportMarkdown(){const rows=await allVisits(),name='PizzaScan-Besuchsarchiv-'+new Date().toISOString().slice(0,10)+'.md';await bridge('save',{name,text:H.archiveToMarkdown(rows)});toast(`${rows.length} Orte als Markdown gesichert.`);}
 async function importJson(){const input=root.document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const f=input.files?.[0];if(!f)return;const data=JSON.parse(await f.text());if(!validArchiveObject(data,H))throw Error('Das ist kein gültiges PizzaScan-Besuchsarchiv.');const n=await importRows(data.visits);toast(`${n} besuchte Orte geladen bzw. zusammengeführt.`);showVisitedLibrary();}catch(e){toast(e.message||'Archiv konnte nicht geladen werden.');}};input.click();}
 function importMarkdown(){openSheet('visit-import','BESUCHSARCHIV · MARKDOWN',`<h1>Markdown-Backup laden</h1><p class="hint">Füge den vollständigen Inhalt eines von PizzaScan erzeugten Markdown-Archivs ein. Vorhandene Einträge werden zusammengeführt.</p><textarea id="visit-md-import" class="visit-import-box" placeholder="# PizzaScan Besuchsarchiv …"></textarea><button id="visit-md-apply" class="primary full">Archiv prüfen & laden</button>`);root.document.getElementById('visit-md-apply').onclick=()=>guarded(async()=>{const rows=H.archiveFromMarkdown(root.document.getElementById('visit-md-import').value),n=await importRows(rows);toast(`${n} Orte aus Markdown geladen.`);showVisitedLibrary();});}
 function summary(r){const e=latestEvent(r);return e?`${Number(e.rating).toFixed(1)}/10 · ${new Date(e.updatedAt).toLocaleDateString(root.document.documentElement.lang||'de')}`:'Besucht';}
 async function showVisitedLibrary(){const rows=(await refreshVisits()).sort((a,b)=>Date.parse(latestEvent(b)?.updatedAt||b.updatedAt||0)-Date.parse(latestEvent(a)?.updatedAt||a.updatedAt||0)),cards=rows.map(r=>{const e=latestEvent(r),note=String(e?.notes||'').trim();return`<article class="visit-library-card"><div><strong translate="no">${esc(r.place?.name||r.placeId)}</strong><small>${esc(summary(r))}</small>${r.place?.address?`<small translate="no">${esc(r.place.address)}</small>`:''}${note?`<p>${esc(note.slice(0,240))}${note.length>240?'…':''}</p>`:''}</div><div class="visit-library-actions"><button class="secondary" data-action="visit-open-place" data-id="${esc(r.placeId)}">Details</button><button class="secondary" data-action="visit-open-review" data-id="${esc(r.placeId)}">Rezension</button></div></article>`;}).join('')||'<div class="empty">Noch keine besuchten und selbst bewerteten Orte gespeichert.</div>';openSheet('visited-library','DEINE BESUCHTEN ORTE',`<div class="visit-library-head"><div><h1>Besucht & bewertet.</h1><p class="hint">Diese Orte bleiben lokal erhalten, auch wenn eine spätere Kartensuche sie gerade nicht liefert.</p></div><span class="visit-count-pill">${rows.length}</span></div><div class="visit-backup-grid"><button class="secondary" data-action="visit-export-json">Backup sichern (.json)</button><button class="secondary" data-action="visit-import-json">Backup laden (.json)</button><button class="text-button" data-action="visit-export-md">Lesbare Kopie (.md)</button><button class="text-button" data-action="visit-import-md">Markdown-Inhalt laden</button></div><div class="visit-library-list">${cards}</div>`);}
 function style(){if(root.document.getElementById('build39-style'))return;const s=root.document.createElement('style');s.id='build39-style';s.textContent=`.visit-badge{display:inline-flex;margin-left:.35rem;padding:.18rem .48rem;border-radius:999px;background:rgba(239,78,39,.12);font-size:.72rem;font-weight:800}.visit-editor{margin:1rem 0;padding:1rem;border:1px solid rgba(120,110,100,.18);border-radius:20px;background:rgba(255,255,255,.62)}.dark .visit-editor{background:rgba(25,25,25,.55)}.visit-editor-grid{display:grid;grid-template-columns:140px 1fr;gap:.75rem;margin:.8rem 0}.visit-editor textarea{min-height:84px}.visit-library-head{display:flex;justify-content:space-between;gap:1rem}.visit-count-pill{min-width:46px;height:46px;border-radius:16px;display:grid;place-items:center;background:#ef4b23;color:#fff;font-weight:900}.visit-backup-grid,.review-portal-grid{display:grid;grid-template-columns:1fr 1fr;gap:.6rem;margin:1rem 0}.visit-library-list{display:grid;gap:.65rem}.visit-library-card{display:flex;justify-content:space-between;gap:.8rem;padding:.85rem;border:1px solid rgba(120,110,100,.16);border-radius:18px;background:rgba(255,255,255,.58)}.dark .visit-library-card{background:rgba(25,25,25,.5)}.visit-library-card strong,.visit-library-card small{display:block}.visit-library-actions{display:flex;flex-direction:column;gap:.4rem;justify-content:center}.visit-import-box{min-height:280px}.review-publish-hub{margin:1rem 0;padding:1rem;border-radius:22px;background:rgba(239,78,39,.07);border:1px solid rgba(239,78,39,.16)}.review-copy-row{display:flex;gap:.55rem;margin:.75rem 0}.review-copy-row button{flex:1}.review-portal-card{display:flex;flex-direction:column;gap:.45rem;padding:.75rem;border-radius:17px;background:rgba(255,255,255,.72);border:1px solid rgba(120,110,100,.14)}.dark .review-portal-card{background:rgba(25,25,25,.62)}.review-portal-card small{opacity:.72;line-height:1.3}.review-portal-card button{width:100%;margin-top:auto}.review-portal-card.mangrove{grid-column:1/-1}.mangrove-actions{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}.portal-copy-open{min-height:48px}.portal-state{font-size:.78rem;opacity:.75}@media(max-width:520px){.review-portal-grid,.visit-backup-grid,.visit-editor-grid,.mangrove-actions{grid-template-columns:1fr}.visit-library-card{flex-direction:column}.visit-library-actions{flex-direction:row}.review-copy-row{flex-direction:column}.review-copy-row button{width:100%}}`;root.document.head.append(s);}
 style();
 try{const q=root.document.querySelector('.map-quick-actions');if(q&&!root.document.getElementById('visited-library-open')){const b=root.document.createElement('button');b.id='visited-library-open';b.className='secondary';b.dataset.action='visit-library';b.innerHTML='📍 Besucht & bewertet <span class="badge">0</span>';q.append(b);}}catch{}
 if(typeof statusBadge==='function'){const base=statusBadge;statusBadge=p=>base(p)+(visits.has(p?.placeId)?'<span class="visit-badge">✓ besucht</span>':'');}
 if(typeof visiblePlaces==='function'){const base=visiblePlaces;visiblePlaces=()=>{const list=base();let cfg;try{cfg=mapConfig();}catch{return list;}return cfg.hideVisited?list.filter(p=>!visits.has(p.placeId)):list;};}
 if(typeof drawMarkers==='function'){const base=drawMarkers;drawMarkers=function(){if(typeof reports==='undefined')return base();const known=new Set(reports.filter(r=>r?.visited&&r?.place).map(r=>r.place.placeId)),extra=[];try{for(const [id,r] of visits)if(!known.has(id)&&r?.place)extra.push({id:'visit-ui:'+id,visited:true,place:r.place});reports.push(...extra);return base();}finally{if(extra.length)reports.splice(reports.length-extra.length,extra.length);}};}
 if(typeof detailsHtml==='function'){const base=detailsHtml;detailsHtml=function(p,...args){const rec=visits.get(p?.placeId),e=latestEvent(rec),rating=e?Number(e.rating).toFixed(1):'',notes=e?.notes||'';return base(p,...args)+`<section class="visit-editor"><h2>📍 Mein Besuch</h2><p class="hint">Speichere den Ort dauerhaft als besucht und selbst bewertet. Dieser Eintrag bleibt privat auf deinem Gerät.</p><div class="visit-editor-grid"><div class="field"><label for="visit-rating">Eigene Bewertung / 10</label><input id="visit-rating" type="number" min="0.1" max="10" step="0.1" inputmode="decimal" value="${esc(rating)}" placeholder="0,1–10,0"></div><div class="field"><label for="visit-notes">Notiz</label><textarea id="visit-notes" maxlength="4000">${esc(notes)}</textarea></div></div><label class="check"><input id="visit-confirm" type="checkbox" ${rec?'checked':''}><span>Ich war hier / habe hier bestellt und möchte diesen Ort in meinem Besuchsarchiv behalten.</span></label><div class="row"><button class="primary" data-action="visit-save" data-id="${esc(p.placeId)}">${rec?'✓ Besuch aktualisieren':'Als besucht & bewertet speichern'}</button><button class="secondary" data-action="visit-review" data-id="${esc(p.placeId)}">Rezension erstellen ↗</button></div></section>`;};}
 async function copyText(text){const value=String(text||'');if(!value.trim())throw Error('Der Rezensionstext ist leer.');try{await bridge('copy',{text:value});return;}catch{}try{await root.navigator.clipboard.writeText(value);return;}catch{}const a=root.document.createElement('textarea');a.value=value;a.style.position='fixed';a.style.opacity='0';root.document.body.append(a);a.focus();a.select();let ok=false;try{ok=root.document.execCommand('copy');}finally{a.remove();}if(!ok)throw Error('Text konnte nicht kopiert werden.');}
 async function openUrl(url){try{await bridge('open',{url});return;}catch{}if(!root.open(url,'_blank','noopener'))throw Error('Portal konnte nicht geöffnet werden.');}
 async function copyOpen(url){await copyText(root.document.getElementById('draft-text')?.value||'');await openUrl(url);toast('Rezension kopiert · Portal geöffnet.');}
 function syncPortals(){const maps=root.document.getElementById('maps-draft'),invalid=!!maps?.disabled,text=root.document.getElementById('draft-text')?.value||'';for(const b of root.document.querySelectorAll('[data-review-portal]'))b.disabled=invalid;const direct=root.document.querySelector('[data-openreviews-publish]');if(direct)direct.disabled=invalid||text.length>1000;const state=root.document.getElementById('portal-state');if(state)state.textContent=invalid?'Vervollständige zuerst Besuchsart, Bewertung, Text und Bestätigung.':`Bereit · ${text.length} Zeichen${text.length<=1000?' · Mangrove-Direktupload möglich':' · für Mangrove-Direktupload auf 1000 Zeichen kürzen'}.`;}
 function portalHub(venue){const body=root.document.getElementById('sheet-body'),maps=root.document.getElementById('maps-draft'),copy=root.document.getElementById('copy-draft');if(!body||!maps||!copy||body.querySelector('.review-publish-hub'))return;const u=portalUrls(venue),direct=body.querySelector('[data-openreviews-publish]'),hub=root.document.createElement('section');hub.className='review-publish-hub';hub.innerHTML=`<h2>Rezension veröffentlichen</h2><p class="hint">Ein Entwurf, mehrere Portale. PizzaScan kopiert den Text und öffnet das gewählte Portal; veröffentlicht wird erst durch dich.</p><div id="review-copy-row" class="review-copy-row"></div><div class="review-portal-grid"><div class="review-portal-card"><strong>🗺️ Google Maps</strong><small>Text kopieren und Google Maps öffnen.</small><div id="portal-google"></div></div><div class="review-portal-card"><strong>Yelp</strong><small>Text kopieren und Yelp für diesen Ort öffnen.</small><button class="secondary portal-copy-open" data-review-portal="yelp">Kopieren & Yelp öffnen ↗</button></div><div class="review-portal-card"><strong>TripAdvisor</strong><small>Text kopieren und TripAdvisor für diesen Ort öffnen.</small><button class="secondary portal-copy-open" data-review-portal="tripadvisor">Kopieren & TripAdvisor öffnen ↗</button></div><div class="review-portal-card mangrove"><strong>🌿 Mangrove / Open Reviews</strong><small>Offenes Rating-Netzwerk. Manuell öffnen oder freiwillig direkt signiert aus PizzaScan veröffentlichen.</small><div class="mangrove-actions"><button class="secondary portal-copy-open" data-review-portal="mangrove">Kopieren & Mangrove öffnen ↗</button><div id="mangrove-direct-slot"></div></div></div></div><p id="portal-state" class="portal-state"></p>`;maps.parentNode?.insertBefore(hub,maps);root.document.getElementById('review-copy-row').append(copy);copy.textContent='📋 Nur Text kopieren';root.document.getElementById('portal-google').append(maps);maps.textContent='Kopieren & Google Maps öffnen ↗';maps.classList.add('portal-copy-open');copy.onclick=()=>guarded(async()=>{if(copy.disabled)return;await copyText(root.document.getElementById('draft-text')?.value||'');toast('Rezension kopiert.');});maps.onclick=()=>guarded(()=>copyOpen(u.google));for(const b of body.querySelectorAll('[data-review-portal]'))b.onclick=()=>guarded(()=>copyOpen(u[b.dataset.reviewPortal]));const slot=root.document.getElementById('mangrove-direct-slot');if(direct){direct.className='primary';direct.textContent='🌿 Direkt bei Mangrove veröffentlichen';slot.append(direct);}else{const enable=root.document.createElement('button');enable.className='secondary';enable.type='button';enable.textContent='Mangrove-Direktupload aktivieren';enable.onclick=()=>showSettings();slot.append(enable);}const sync=()=>setTimeout(syncPortals,0);body.addEventListener('input',sync);body.addEventListener('change',sync);body.addEventListener('click',sync);syncPortals();}
 if(typeof showDraft==='function'){const base=showDraft;showDraft=function(source){const venue=source?.place||source;let had=false;try{had=!!JSON.parse(root.localStorage?.getItem('pizzascan-drafts-v1')||'{}')?.[venue?.placeId];}catch{}const out=base(source);if(venue?.placeId){portalHub(venue);if(!had)getVisit(venue.placeId).then(rec=>{const e=latestEvent(rec);if(!e||!root.document.querySelector('.review-publish-hub'))return;const rating=root.document.getElementById('review-rating'),notes=root.document.getElementById('review-notes'),checked=root.document.getElementById('review-visited');if(rating&&!rating.value){rating.value=Number(e.rating).toFixed(1);rating.dispatchEvent(new Event('input',{bubbles:true}));}if(notes&&!notes.value&&e.notes){notes.value=e.notes;notes.dispatchEvent(new Event('input',{bubbles:true}));}if(checked&&!checked.checked){checked.checked=true;checked.dispatchEvent(new Event('change',{bubbles:true}));}syncPortals();}).catch(()=>{});}return out;};}
 if(typeof handleMapAction==='function'){const base=handleMapAction;handleMapAction=async function(b){const a=b?.dataset?.action,id=b?.dataset?.id;if(a==='visit-library')return showVisitedLibrary();if(a==='visit-save'){const p=placeById(id)||mapPool.find(x=>x.placeId===id);if(!p)return;if(!root.document.getElementById('visit-confirm')?.checked)throw Error('Bitte bestätige zuerst deinen Besuch.');const r=await saveVisit(p,root.document.getElementById('visit-rating')?.value,root.document.getElementById('visit-notes')?.value||'');toast('Besuch und Bewertung dauerhaft gespeichert.');await refreshVisits(true);return r;}if(a==='visit-review'){const p=placeById(id)||mapPool.find(x=>x.placeId===id),e=latestEvent(visits.get(id)),rating=e?.rating??Number(root.document.getElementById('visit-rating')?.value),notes=e?.notes??(root.document.getElementById('visit-notes')?.value||'');return showDraft({place:p,own:rating,notes,visited:true});}if(a==='visit-open-place'){closeSheet();return showPlace(id);}if(a==='visit-open-review'){const r=visits.get(id),e=latestEvent(r);closeSheet();return showDraft({place:r?.place,own:e?.rating,notes:e?.notes||'',visited:true});}if(a==='visit-export-json')return exportJson();if(a==='visit-import-json')return importJson();if(a==='visit-export-md')return exportMarkdown();if(a==='visit-import-md')return importMarkdown();return base(b);};}
 root.PizzaBuild39Runtime={blockedProvider,portalUrls,latestEvent,refreshVisits,saveVisit,showVisitedLibrary,exportJson,exportMarkdown};refreshVisits(true).catch(e=>console.warn('PizzaScan visit UI unavailable',e));return true;
}
return{BLOCKED_PROVIDER_HOST,MANUAL_EVENT_PREFIX,hostOf,blockedProvider,stripProviderArray,latestEvent,mangroveSubject,portalUrls,validArchiveObject,install};
});
