'use strict';
function readDraftRecords(){const value=read(DRAFTS,{});return value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value)):{};}
function draftEntries(){return Object.values(readDraftRecords()).flatMap(v=>{try{const d=PizzaDrafts.entry(v);return PizzaDrafts.hasContent(d)?[d]:[];}catch{return [];}}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
function renderDraftBadge(){const count=draftEntries().length;for(const el of document.querySelectorAll('[data-draft-count]'))el.textContent=count;}
function exportDraft(d){return bridge('save',{name:'PizzaScan-Rezension-'+d.place.placeId.replace(/[^a-zA-Z0-9-]/g,'_')+'.json',text:JSON.stringify(PizzaDrafts.backup(d),null,2)});}
function showDrafts(){
 detailRequest?.abort();const entries=draftEntries();
 openSheet('draft-list','DEINE PRIVATEN ENTWÜRFE',`<h1>Deine Rezensionen.</h1><p class="lead">Hier findest du deine gespeicherten Entwürfe – auch ohne Internet und ohne erneute Restaurantsuche.</p><div class="draft-list-tools"><button id="draft-new" class="primary">Restaurant auf Karte wählen</button><button id="draft-import-open" class="secondary">Entwurf aus JSON wiederherstellen</button><input id="draft-import" type="file" accept="application/json,.json" hidden></div><label for="draft-search">Entwürfe durchsuchen</label><input id="draft-search" type="search" placeholder="Restaurant oder Text" autocomplete="off"><p id="draft-list-count" class="hint" role="status"></p><div id="draft-list" class="cards"></div><p class="hint">Ein JSON-Export sichert genau diesen Entwurf mit Bausteinen und bearbeitetem Text. Fotos und KI-Analysen sind nicht enthalten. Veröffentlicht wird ausschließlich von dir in Google Maps.</p>`);
 function render(){const q=$('draft-search').value.trim().toLocaleLowerCase('de-DE'),visible=entries.filter(d=>(d.place.name+' '+d.place.address+' '+d.text).toLocaleLowerCase('de-DE').includes(q));$('draft-list-count').textContent=`${visible.length} von ${entries.length} Entwürfen`;$('draft-list').innerHTML=visible.map(d=>`<article class="card draft-card"><button class="draft-open" data-draft-open="${esc(d.place.placeId)}"><strong translate="no">${esc(d.place.name)}</strong><small>${esc(PizzaReview.modes[d.state.mode]||'Besuchsart noch offen')} · ${d.state.own===null?'Noch ohne Gesamtwertung':d.state.own.toFixed(1)+'/10'}${d.updatedAt?' · '+new Date(d.updatedAt).toLocaleDateString(document.documentElement.lang||'de'):''}</small><span translate="no">${esc(d.text.slice(0,160))}${d.text.length>160?' …':''}</span><b>Weiter bearbeiten ↗</b></button><div class="card-actions"><button class="text-button" data-draft-export="${esc(d.place.placeId)}">JSON exportieren</button><button class="text-button danger" data-draft-remove="${esc(d.place.placeId)}">Löschen</button></div></article>`).join('')||empty(entries.length?'Keine passenden Entwürfe.':'Wähle ein Restaurant auf der Karte und öffne den Rezensionsbaukasten. Sobald du etwas einträgst, erscheint dein Entwurf hier.');}
 $('draft-search').oninput=render;$('draft-new').onclick=()=>navigate('map');$('draft-import-open').onclick=()=>$('draft-import').click();
 $('draft-import').onchange=()=>guarded(async()=>{const file=$('draft-import').files[0];if(!file)return;try{if(file.size>100000)throw Error('Bitte eine einzelne Rezensionsdatei unter 100 KB auswählen.');let input;try{input=JSON.parse(await file.text());}catch{throw Error('Die ausgewählte Datei ist kein gültiges JSON.');}const d=PizzaDrafts.restore(input),all=readDraftRecords();if(!confirm(`Entwurf für „${d.place.name}“ wiederherstellen?${Object.hasOwn(all,d.place.placeId)?' Der vorhandene Entwurf dieses Restaurants wird ersetzt.':''}`))return;d.updatedAt=new Date().toISOString();all[d.place.placeId]=d;if(!placeService.write(DRAFTS,all))throw Error('Der Entwurf konnte nicht gespeichert werden. Bitte Gerätespeicher prüfen.');renderDraftBadge();showDrafts();toast('Rezensionsentwurf wiederhergestellt');}finally{if($('draft-import'))$('draft-import').value='';}});
 $('sheet-body').onclick=e=>guarded(async()=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.draftOpen||b.dataset.draftExport||b.dataset.draftRemove,d=entries.find(v=>v.place.placeId===id);if(!d)return;if(b.dataset.draftOpen)showDraft(d.place);else if(b.dataset.draftExport)await exportDraft(d);else if(b.dataset.draftRemove&&confirm(`Entwurf für „${d.place.name}“ auf diesem Gerät löschen?`)){const all=readDraftRecords();delete all[id];if(!placeService.write(DRAFTS,all))throw Error('Entwurf konnte nicht gelöscht werden');renderDraftBadge();showDrafts();}});
 render();
}
