/* PizzaScan map hotfix: first-load discovery + stable touch popups. */
'use strict';
let popupPlaceId='',pendingAutoRefresh=false,hotfixFirstLoad=true;
function hasOpenPopup(){return !!popupPlaceId;}
function lockPopup(id){popupPlaceId=id;pendingAutoRefresh=false;clearTimeout(queryTimer);}
function unlockPopup(id){if(id&&popupPlaceId&&popupPlaceId!==id)return;const shouldRefresh=pendingAutoRefresh&&mapConfig().autoSearch;popupPlaceId='';pendingAutoRefresh=false;if(shouldRefresh){clearTimeout(queryTimer);queryTimer=setTimeout(()=>loadPlaces(),220);}}
const baseLoadPlaces=loadPlaces;
loadPlaces=async function(options={}){const first=hotfixFirstLoad;hotfixFirstLoad=false;await baseLoadPlaces({...options,force:options.force===true||first});if(first&&!places.length&&!mapLoading){settings.filters={...mapConfig(),radius:10,autoSearch:false};saveSettings();$('map-status').textContent='Noch keine Treffer – Suchbereich wird erweitert …';await baseLoadPlaces({force:true});if(!places.length&&!mapError){mapError='Im Startbereich wurden noch keine Pizza-Orte gefunden. Aktiviere GPS oder suche nach Stadt bzw. Pizzeria.';renderPlaces();}}};
drawMarkers=function(){if(!markers||hasOpenPopup())return;markers.clearLayers();const visited=new Set(reports.filter(r=>r.visited&&r.place).map(r=>r.place.placeId));for(const p of visiblePlaces()){const h=Hours.status(p),isSaved=saved.some(x=>x.placeId===p.placeId),isVisited=visited.has(p.placeId),icon=L.divIcon({className:'emoji-marker '+h.state,html:`<span>${PlaceData.TYPES[p.type]?.emoji||'🍕'}</span>${isSaved?'<b>⭐</b>':isVisited?'<b>✓</b>':''}`,iconSize:[38,42],iconAnchor:[19,36],popupAnchor:[0,-32]});const content=document.createElement('div');content.className='venue-popup';content.innerHTML=`<div class="venue-popup-top"><span class="venue-popup-emoji" aria-hidden="true">${PlaceData.TYPES[p.type]?.emoji||'🍕'}</span><div class="venue-popup-heading"><strong>${esc(p.name)}</strong><small>${esc(p.address||PlaceData.TYPES[p.type]?.name||'Pizza-Ort')}</small></div></div><div class="venue-popup-meta">${statusBadge(p)}<small>${esc(h.note)}</small></div><div class="venue-popup-actions"><button class="secondary" data-action="place" data-id="${esc(p.placeId)}">Details</button><button class="primary" data-action="review-builder" data-id="${esc(p.placeId)}">Rezension</button><button class="secondary" data-action="directions" data-id="${esc(p.placeId)}">Route</button></div>`;for(const name of ['click','dblclick','mousedown','mouseup','pointerdown','pointerup','touchstart','touchend'])content.addEventListener(name,e=>e.stopPropagation(),{passive:true});const marker=L.marker([p.lat,p.lng],{icon,title:p.name,alt:p.name,riseOnHover:true}).addTo(markers).bindPopup(content,{maxWidth:320,minWidth:240,autoPan:true,autoPanPadding:[24,32],keepInView:true,className:'pizza-popup',closeButton:false});marker.on('popupopen',()=>lockPopup(p.placeId));marker.on('popupclose',()=>unlockPopup(p.placeId));}};
initMap=function(){const state=read('pizzascan-map-view-v1',{}),center=C.coords(state.lat,state.lng)?[state.lat,state.lng]:[53.5511,9.9937],zoom=Number.isFinite(state.zoom)&&state.zoom>=11&&state.zoom<=19?state.zoom:14;map=L.map('map',{zoomControl:false,attributionControl:true,tapTolerance:18}).setView(center,zoom);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);markers=L.layerGroup().addTo(map);$('map-fullscreen').onclick=()=>setMapFullscreen(true);$('fs-back').onclick=()=>setMapFullscreen(false);$('fs-search').onclick=toggleFullscreenSearch;$('fs-filter').onclick=showFilters;$('fs-gps').onclick=gps;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mapFullscreen&&!$('sheet').open){e.preventDefault();setMapFullscreen(false);}});const cache=read('pizzascan-map-cache-v3',{});try{mapPool=C.importPlaces(cache.places||read('pizzascan-map-cache-v2',[]));mapAreas=Array.isArray(cache.areas)?cache.areas.filter(a=>a.center&&C.coords(a.center.lat,a.center.lng)&&Number.isFinite(a.time)&&Number.isFinite(a.radius)):[];}catch{mapPool=[];mapAreas=[];}refreshArea();map.on('moveend',()=>{const c=mapCenter();placeService.write('pizzascan-map-view-v1',{...c,zoom:map.getZoom()});if(hasOpenPopup()){pendingAutoRefresh=mapConfig().autoSearch;return;}refreshArea();clearTimeout(queryTimer);if(mapConfig().autoSearch)queryTimer=setTimeout(()=>loadPlaces(),1100);});map.on('popupclose',()=>unlockPopup());$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(localSuggestions,120);});$('filter-open').onclick=showFilters;$('open-filter').onclick=()=>{settings.filters={...mapConfig(),onlyOpen:!mapConfig().onlyOpen};saveSettings();renderPlaces();};$('map-refresh').onclick=()=>loadPlaces({force:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!hasOpenPopup())renderPlaces();});setInterval(()=>{if(!document.hidden&&!hasOpenPopup())renderPlaces();},60000);};
