/* Localize static long text/attributes that are split across DOM nodes or can be rewritten by runtime UI. */
(function(){
'use strict';
const copy={
 de:{welcome:'Finden. Fotografieren.<br>Pizza verstehen.',notice:'Für die Fotoanalyse kommt ein Offline-Modell dazu: standardmäßig CLIP ViT-B/32 (ca. 160 MB). Es wird erst nach deiner Bestätigung separat heruntergeladen und anschließend dauerhaft im privaten PizzaScan-App-Speicher abgelegt. Dein Foto bleibt für die Analyse auf diesem Gerät.',hint:'Standortstart und App-Sprache kannst du in den Einstellungen ändern. Kartenanbieter erhalten den angefragten Suchbereich. Fotoanalysen und Rezensionsentwürfe bleiben auf deinem Gerät.',legend:'Restaurants & Pizza-Orte: 🍕 Pizzeria · 🍝 Trattoria · 🍽️ Ristorante · 🍷 Osteria · ☕ Café · 🍔 Imbiss · 🚚 Foodtruck · 🤖 Pizzaautomat · ⭐ Gemerkt · ✓ Besucht · 📍 Dein Standort',mapAria:'Karte mit Restaurants und weiteren Pizza-Orten',navAria:'Hauptnavigation',searchAria:'Restaurant, Pizzeria, Café, Stadt oder Adresse suchen',searchPlaceholder:'Pizzeria, Trattoria, Ristorante, Osteria …',brandAria:'PizzaScan Karte'},
 en:{welcome:'Find. Photograph.<br>Understand pizza.',notice:'Photo analysis uses an additional offline model: CLIP ViT-B/32 by default (about 160 MB). It is downloaded separately only after your confirmation and then stored persistently in PizzaScan’s private app storage. Your photo remains on this device for analysis.',hint:'You can change location startup and the app language in Settings. Map providers receive the requested search area. Photo analyses and review drafts remain on your device.',legend:'Restaurants & pizza places: 🍕 Pizzeria · 🍝 Trattoria · 🍽️ Ristorante · 🍷 Osteria · ☕ Café · 🍔 Fast food · 🚚 Food truck · 🤖 Pizza vending · ⭐ Saved · ✓ Visited · 📍 Your location',mapAria:'Map with restaurants and additional pizza places',navAria:'Main navigation',searchAria:'Search restaurant, pizzeria, café, city or address',searchPlaceholder:'Pizzeria, trattoria, Italian restaurant, pizza …',brandAria:'PizzaScan map'},
 it:{welcome:'Trova. Fotografa.<br>Capisci la pizza.',notice:'L’analisi foto utilizza un modello offline aggiuntivo: CLIP ViT-B/32 per impostazione predefinita (circa 160 MB). Viene scaricato separatamente solo dopo la tua conferma e poi salvato in modo persistente nella memoria privata dell’app PizzaScan. La foto resta su questo dispositivo per l’analisi.',hint:'Puoi modificare l’avvio con posizione e la lingua dell’app nelle Impostazioni. I fornitori della mappa ricevono l’area di ricerca richiesta. Analisi foto e bozze di recensione restano sul dispositivo.',legend:'Ristoranti e locali pizza: 🍕 Pizzeria · 🍝 Trattoria · 🍽️ Ristorante · 🍷 Osteria · ☕ Caffè · 🍔 Fast food · 🚚 Food truck · 🤖 Distributore pizza · ⭐ Salvati · ✓ Visitati · 📍 La tua posizione',mapAria:'Mappa con ristoranti e locali pizza aggiuntivi',navAria:'Navigazione principale',searchAria:'Cerca ristorante, pizzeria, caffè, città o indirizzo',searchPlaceholder:'Pizzeria, trattoria, ristorante, osteria …',brandAria:'Mappa PizzaScan'},
 es:{welcome:'Encuentra. Fotografía.<br>Entiende la pizza.',notice:'El análisis de fotos utiliza un modelo offline adicional: CLIP ViT-B/32 de forma predeterminada (unos 160 MB). Solo se descarga por separado después de tu confirmación y después se guarda de forma persistente en el almacenamiento privado de PizzaScan. Tu foto permanece en este dispositivo para el análisis.',hint:'Puedes cambiar el inicio con ubicación y el idioma de la app en Ajustes. Los proveedores del mapa reciben el área de búsqueda solicitada. Los análisis de fotos y borradores de reseñas permanecen en tu dispositivo.',legend:'Restaurantes y lugares de pizza: 🍕 Pizzería · 🍝 Trattoria · 🍽️ Ristorante · 🍷 Osteria · ☕ Café · 🍔 Comida rápida · 🚚 Food truck · 🤖 Máquina de pizza · ⭐ Guardados · ✓ Visitados · 📍 Tu ubicación',mapAria:'Mapa con restaurantes y lugares de pizza adicionales',navAria:'Navegación principal',searchAria:'Buscar restaurante, pizzería, café, ciudad o dirección',searchPlaceholder:'Pizzería, trattoria, restaurante italiano …',brandAria:'Mapa de PizzaScan'},
 fr:{welcome:'Trouvez. Photographiez.<br>Comprenez la pizza.',notice:'L’analyse photo utilise un modèle hors ligne supplémentaire : CLIP ViT-B/32 par défaut (environ 160 Mo). Il n’est téléchargé séparément qu’après votre confirmation, puis stocké de façon persistante dans l’espace privé de PizzaScan. Votre photo reste sur cet appareil pour l’analyse.',hint:'Vous pouvez modifier le démarrage avec localisation et la langue de l’application dans les Paramètres. Les fournisseurs de carte reçoivent la zone de recherche demandée. Les analyses photo et brouillons d’avis restent sur votre appareil.',legend:'Restaurants et lieux de pizza : 🍕 Pizzeria · 🍝 Trattoria · 🍽️ Ristorante · 🍷 Osteria · ☕ Café · 🍔 Restauration rapide · 🚚 Food truck · 🤖 Distributeur de pizza · ⭐ Enregistrés · ✓ Visités · 📍 Votre position',mapAria:'Carte avec restaurants et lieux de pizza supplémentaires',navAria:'Navigation principale',searchAria:'Rechercher restaurant, pizzeria, café, ville ou adresse',searchPlaceholder:'Pizzeria, trattoria, restaurant italien …',brandAria:'Carte PizzaScan'}
};
function attr(el,name,value){if(el&&el.getAttribute(name)!==value)el.setAttribute(name,value);}
function text(el,value){if(el&&el.textContent!==value)el.textContent=value;}
function html(el,value){if(el&&el.innerHTML!==value)el.innerHTML=value;}
function language(){const l=String(globalThis.PizzaI18n?.language||document.documentElement.lang||'de').slice(0,2).toLowerCase();return copy[l]?l:'de';}
function apply(){
 const c=copy[language()],welcome=document.querySelector('#welcome h1'),notice=document.querySelector('#welcome .notice'),hint=document.querySelector('#welcome .hint'),legend=document.querySelector('.map-legend p'),search=document.getElementById('search');
 html(welcome,c.welcome);text(notice,c.notice);text(hint,c.hint);text(legend,c.legend);
 attr(document.getElementById('map'),'aria-label',c.mapAria);attr(document.querySelector('.dock'),'aria-label',c.navAria);
 attr(search,'aria-label',c.searchAria);attr(search,'placeholder',c.searchPlaceholder);attr(document.querySelector('.brand'),'aria-label',c.brandAria);
}
function installObservers(){
 apply();
 const search=document.getElementById('search');
 if(search&&!search.__pizzaStaticI18nObserver){search.__pizzaStaticI18nObserver=true;new MutationObserver(()=>queueMicrotask(apply)).observe(search,{attributes:true,attributeFilter:['placeholder','aria-label']});}
 if(!document.documentElement.__pizzaStaticI18nObserver){document.documentElement.__pizzaStaticI18nObserver=true;new MutationObserver(()=>queueMicrotask(apply)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installObservers,{once:true});else installObservers();
setTimeout(apply,0);
})();
