/* Localize static long text that is split across DOM nodes and therefore cannot be translated token-by-token. */
(function(){
'use strict';
const copy={
 en:{welcome:'Find. Photograph.<br>Understand pizza.',notice:'Photo analysis uses an additional offline model: CLIP ViT-B/32 by default (about 160 MB). It is downloaded separately only after your confirmation and then stored persistently in PizzaScan’s private app storage. Your photo remains on this device for analysis.',hint:'You can change location startup and the app language in Settings. Map providers receive the requested search area. Photo analyses and review drafts remain on your device.',legend:'🍕 Pizzeria · ☕ Café · 🍔 Fast food · 🚚 Food truck · 🤖 Pizza vending machine · 🍽️ Other places · ⭐ Saved · ✓ Visited · 📍 Your location',mapAria:'Map with pizzerias',navAria:'Main navigation',searchAria:'Search restaurant, pizzeria, pizza place, city or address',brandAria:'PizzaScan map'},
 it:{welcome:'Trova. Fotografa.<br>Capisci la pizza.',notice:'L’analisi foto utilizza un modello offline aggiuntivo: CLIP ViT-B/32 per impostazione predefinita (circa 160 MB). Viene scaricato separatamente solo dopo la tua conferma e poi salvato in modo persistente nella memoria privata dell’app PizzaScan. La foto resta su questo dispositivo per l’analisi.',hint:'Puoi modificare l’avvio con posizione e la lingua dell’app nelle Impostazioni. I fornitori della mappa ricevono l’area di ricerca richiesta. Analisi foto e bozze di recensione restano sul dispositivo.',legend:'🍕 Pizzeria · ☕ Caffè · 🍔 Fast food · 🚚 Food truck · 🤖 Distributore pizza · 🍽️ Altri luoghi · ⭐ Salvati · ✓ Visitati · 📍 La tua posizione',mapAria:'Mappa con pizzerie',navAria:'Navigazione principale',searchAria:'Cerca ristorante, pizzeria, locale pizza, città o indirizzo',brandAria:'Mappa PizzaScan'},
 es:{welcome:'Encuentra. Fotografía.<br>Entiende la pizza.',notice:'El análisis de fotos utiliza un modelo offline adicional: CLIP ViT-B/32 de forma predeterminada (unos 160 MB). Solo se descarga por separado después de tu confirmación y después se guarda de forma persistente en el almacenamiento privado de PizzaScan. Tu foto permanece en este dispositivo para el análisis.',hint:'Puedes cambiar el inicio con ubicación y el idioma de la app en Ajustes. Los proveedores del mapa reciben el área de búsqueda solicitada. Los análisis de fotos y borradores de reseñas permanecen en tu dispositivo.',legend:'🍕 Pizzería · ☕ Café · 🍔 Comida rápida · 🚚 Food truck · 🤖 Máquina de pizza · 🍽️ Otros lugares · ⭐ Guardados · ✓ Visitados · 📍 Tu ubicación',mapAria:'Mapa con pizzerías',navAria:'Navegación principal',searchAria:'Buscar restaurante, pizzería, lugar de pizza, ciudad o dirección',brandAria:'Mapa de PizzaScan'},
 fr:{welcome:'Trouvez. Photographiez.<br>Comprenez la pizza.',notice:'L’analyse photo utilise un modèle hors ligne supplémentaire : CLIP ViT-B/32 par défaut (environ 160 Mo). Il n’est téléchargé séparément qu’après votre confirmation, puis stocké de façon persistante dans l’espace privé de PizzaScan. Votre photo reste sur cet appareil pour l’analyse.',hint:'Vous pouvez modifier le démarrage avec localisation et la langue de l’application dans les Paramètres. Les fournisseurs de carte reçoivent la zone de recherche demandée. Les analyses photo et brouillons d’avis restent sur votre appareil.',legend:'🍕 Pizzeria · ☕ Café · 🍔 Restauration rapide · 🚚 Food truck · 🤖 Distributeur de pizza · 🍽️ Autres lieux · ⭐ Enregistrés · ✓ Visités · 📍 Votre position',mapAria:'Carte avec pizzerias',navAria:'Navigation principale',searchAria:'Rechercher restaurant, pizzeria, lieu de pizza, ville ou adresse',brandAria:'Carte PizzaScan'}
};
function apply(){const l=globalThis.PizzaI18n?.language||'de';if(l==='de'||!copy[l])return;const c=copy[l],welcome=document.querySelector('#welcome h1'),notice=document.querySelector('#welcome .notice'),hint=document.querySelector('#welcome .hint'),legend=document.querySelector('.map-legend p');if(welcome)welcome.innerHTML=c.welcome;if(notice)notice.textContent=c.notice;if(hint)hint.textContent=c.hint;if(legend)legend.textContent=c.legend;document.getElementById('map')?.setAttribute('aria-label',c.mapAria);document.querySelector('.dock')?.setAttribute('aria-label',c.navAria);document.getElementById('search')?.setAttribute('aria-label',c.searchAria);document.querySelector('.brand')?.setAttribute('aria-label',c.brandAria);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
