(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./core.js'):root.PizzaCore);if(typeof module==='object'&&module.exports)module.exports=api;else root.PizzaPlaces=api;})(globalThis,function(C){
'use strict';
const TYPES={pizzeria:{emoji:'🍕',name:'Pizzeria / Restaurant'},cafe:{emoji:'☕',name:'Café'},fast_food:{emoji:'🍔',name:'Imbiss / Schnellrestaurant'},food_truck:{emoji:'🚚',name:'Foodtruck'},vending_pizza:{emoji:'🤖',name:'Pizzaautomat'},other:{emoji:'🍽️',name:'Weitere Pizza-Orte'}};
const providers=['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter'];
const defaults={onlyOpen:false,unknownHours:false,includeItalian:true,radius:3,types:Object.keys(TYPES),autoSearch:true,sort:'distance',travelMode:'walking',hideVisited:false};
const text=v=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function address(t){return t['addr:full']||[[t['addr:street']||t['addr:place'],t['addr:housenumber']].filter(Boolean).join(' '),[t['addr:postcode'],t['addr:city']||t['addr:town']||t['addr:village']].filter(Boolean).join(' ')].filter(Boolean).join(', ');}
function normalize(element,options={}){const t=element.tags||{},lat=element.lat??element.center?.lat,lng=element.lon??element.center?.lon;if(!C.coords(lat,lng)||!['node','way','relation'].includes(element.type)||!/^\d+$/.test(String(element.id)))return null;if(t.disused==='yes'||t.abandoned==='yes'||['disused','abandoned','demolished','construction'].includes(t.amenity))return null;
 const confirmed=/pizza|pizzeria|pizzaria/i.test([t.cuisine,t.name,t.brand,t.vending,t.speciality].filter(Boolean).join(' '))||t['vending:pizza']==='yes';const possible=/italian/i.test(t.cuisine||'')&&/^(restaurant|cafe|fast_food|food_truck|bar|pub|biergarten|takeaway|food_court)$/.test(t.amenity||'');if(!confirmed&&!possible&&!options.allowNamed)return null;
 const type=/pizza/i.test(t.vending||'')||t['vending:pizza']==='yes'?'vending_pizza':t.amenity==='food_truck'||t.mobile==='yes'?'food_truck':['cafe','fast_food'].includes(t.amenity)?t.amenity:['restaurant','takeaway'].includes(t.amenity)||!t.amenity?'pizzeria':'other';
 return C.place({placeId:element.type+'-'+element.id,name:t.name||t.brand||(type==='vending_pizza'?'Pizzaautomat':'Pizza-Ort ohne Namen'),lat,lng,type,openingHours:t.opening_hours||'',website:t.website||t['contact:website'],phone:t.phone||t['contact:phone']||t.mobile_phone,address:address(t),cuisine:t.cuisine||'',menu:t['website:menu']||t['contact:menu']||t['menu:website'],description:t['description:de']||t.description||'',tags:t,country:t['addr:country']||'',state:t['addr:state']||'',pizzaEvidence:confirmed?'confirmed':possible?'possible':'search',updatedAt:new Date().toISOString(),dataSource:'OpenStreetMap'});
}
function fromOverpass(elements,options){if(!Array.isArray(elements))throw Error('Ungültige Kartendaten');return merge([],elements.map(e=>normalize(e,options)).filter(Boolean));}
function merge(old,incoming){const result=new Map(old.map(p=>[p.placeId,p]));for(const p of incoming){const before=result.get(p.placeId);if(!before){result.set(p.placeId,C.place(p));continue;}const merged={...before,...p,tags:{...before.tags,...p.tags}};for(const key of ['address','country','state','website','phone','menu','description','openingHours','detailsAt'])if(!p[key]&&before[key])merged[key]=before[key];result.set(p.placeId,C.place(merged));}return [...result.values()];}
function query(center,radius,bounds){if(!C.coords(center.lat,center.lng))throw Error('Ungültiger Suchmittelpunkt');const area=radius?`around:${Math.round(Math.min(10,Math.max(.5,radius))*1000)},${center.lat},${center.lng}`:[bounds.south,bounds.west,bounds.north,bounds.east].join(',');return `[out:json][timeout:15];(nwr["cuisine"~"pizza|pizzeria|italian",i](${area});nwr["amenity"~"restaurant|fast_food|cafe|food_truck|bar|pub|biergarten|takeaway|food_court"]["name"~"pizza|pizzeria|pizzaria",i](${area});nwr["vending"~"pizza",i](${area});nwr["vending:pizza"="yes"](${area}););out body center;`;}
function detailQuery(id){const m=/^(node|way|relation)-(\d+)$/.exec(id);if(!m)throw Error('Kein gültiger OpenStreetMap-Ort');return `[out:json][timeout:15];${m[1]}(${m[2]});out body center;`;}
function within(p,center,radius,bounds){return radius?C.distance(center,p)<=radius:p.lat>=bounds.south&&p.lat<=bounds.north&&(bounds.west<=bounds.east?p.lng>=bounds.west&&p.lng<=bounds.east:p.lng>=bounds.west||p.lng<=bounds.east);}
function rank(p,q,center){const n=text(p.name),words=text(q).split(' ').filter(Boolean);let score=n===text(q)?1000:0;for(const w of words){if(n.split(' ').includes(w))score+=100;else if(n.includes(w))score+=45;else if(text(p.address).includes(w))score+=15;else return -1;}return score-Math.min(20,center?C.distance(center,p):0);}
function suggestions(list,q,center){return [...new Map(list.map(p=>[p.placeId,p])).values()].map(p=>({p,score:rank(p,q,center)})).filter(x=>x.score>=0).sort((a,b)=>b.score-a.score).slice(0,8).map(x=>x.p);}
function filter(list,settings,context,hours){return list.filter(p=>settings.types.includes(p.type)&&(!settings.onlyOpen||hours(p).state==='open'||settings.unknownHours&&hours(p).state==='unknown')&&(settings.includeItalian||p.pizzaEvidence==='confirmed')&&(!settings.hideVisited||!context.visited?.has(p.placeId)));}
function fromPhoton(data){if(!Array.isArray(data?.features))throw Error('Ungültige Suchantwort');return data.features.flatMap(f=>{const p=f.properties||{},[lng,lat]=f.geometry?.coordinates||[];if(!C.coords(lat,lng)||!p.name)return [];const type={N:'node',W:'way',R:'relation',node:'node',way:'way',relation:'relation'}[p.osm_type];const tags={name:p.name,'addr:street':p.street||'','addr:housenumber':p.housenumber||'','addr:postcode':p.postcode||'','addr:city':p.city||p.town||p.village||'','addr:country':p.countrycode||'','addr:state':p.state||''};if(p.osm_key)tags[p.osm_key]=p.osm_value||'';const food=/^(restaurant|fast_food|cafe|food_truck|pub|bar|takeaway|biergarten|food_court|vending_machine)$/.test(p.osm_value||'');const normalized=type&&p.osm_id?normalize({type,id:p.osm_id,lat,lon:lng,tags},{allowNamed:food}):null;return [{name:p.name,lat,lng,address:address(tags)||[p.city,p.state,p.country].filter(Boolean).join(', '),kind:food?'venue':'location',place:food?normalized:null,osmId:type&&p.osm_id?type+'-'+p.osm_id:'',country:(p.countrycode||'').toLowerCase(),state:p.state||''}];});}
const nice={yes:'Ja',no:'Nein',only:'Nur dieses Angebot',limited:'Eingeschränkt',designated:'Ausgewiesen',customers:'Für Gäste',public:'Öffentlich',permissive:'Erlaubt',unknown:'Unbekannt'};
function features(p){const t=p.tags||{};const fields=[['Küche',p.cuisine?.replaceAll(';',', ')],['Lieferung',nice[t.delivery]||t.delivery],['Mitnehmen',nice[t.takeaway]||t.takeaway],['Vor Ort essen',nice[t['diet:in_place']]||nice[t.dine_in]||t.dine_in],['Außenplätze',nice[t.outdoor_seating]||t.outdoor_seating],['Rollstuhl',nice[t.wheelchair]||t.wheelchair],['Vegetarisch',nice[t['diet:vegetarian']]||t['diet:vegetarian']],['Vegan',nice[t['diet:vegan']]||t['diet:vegan']],['Glutenfrei',nice[t['diet:gluten_free']]||t['diet:gluten_free']],['Sitzplätze',t.capacity],['WLAN',nice[t.internet_access]||t.internet_access],['Marke',t.brand],['Betreiber',t.operator],['Reservierung',nice[t.reservation]||t.reservation],['E-Mail',t['contact:email']||t.email]];const payments=Object.entries(t).filter(([k,v])=>k.startsWith('payment:')&&v==='yes').map(([k])=>({cash:'Bargeld',credit_cards:'Kreditkarte',debit_cards:'Debitkarte',girocard:'Girocard',visa:'Visa',mastercard:'Mastercard',contactless:'Kontaktlos'}[k.slice(8)]||k.slice(8))).join(', ');if(payments)fields.push(['Bezahlung',payments]);return fields.filter(x=>x[1]);}
class Service{
 constructor(fetcher=globalThis.fetch?.bind(globalThis),storage=globalThis.localStorage){this.fetcher=fetcher;this.storage=storage;this.lastPhoton=0;this.photonQueue=Promise.resolve();this.cache=new Map();this.preferred=providers.indexOf(this.read('pizzascan-map-provider-v1'));if(this.preferred<0)this.preferred=0;}
 async json(url,options={},signal,timeout=18000){if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');const ctl=new AbortController(),abort=()=>ctl.abort();signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,timeout);try{const r=await this.fetcher(url,{...options,signal:ctl.signal,headers:{Accept:'application/json',...options.headers}});if(!r.ok){const error=Error('Dienst antwortet mit HTTP '+r.status);error.status=r.status;error.detail=(await r.text?.())?.slice(0,800)||'';throw error;}const d=await r.json();if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');return d;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
 async overpass(q,{signal,onStatus}={}){this.lastErrors=[];const order=[this.preferred,1-this.preferred];for(let n=0;n<order.length;n++){if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');onStatus?.(n===0?'Pizzerien werden geladen …':'Weitere Kartenquelle wird abgefragt …');try{const index=order[n],data=await this.json(providers[index],{method:'POST',body:new URLSearchParams({data:q})},signal,n===0?18000:22000);if(!Array.isArray(data.elements)||data.remark)throw Error(data.remark||'Unvollständige Kartendaten');this.preferred=index;this.write('pizzascan-map-provider-v1',providers[index]);return {data,source:new URL(providers[index]).hostname};}catch(e){this.lastErrors.push({source:new URL(providers[order[n]]).hostname,message:e.message,detail:e.detail||''});if(signal?.aborted)throw e;if(n===order.length-1)throw Error('Beide Kartenquellen sind momentan nicht erreichbar. Bitte erneut versuchen.');}}}
 async photon(q,center,{signal,force=false}={}){const key=text(q)+'|'+center.lat.toFixed(3)+'|'+center.lng.toFixed(3),stored=this.cache.get(key)||this.read('pizzascan-search-'+key);if(!force&&stored&&Date.now()-stored.time<86400000)return stored.items;
 const run=async()=>{if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');await new Promise(r=>setTimeout(r,Math.max(0,1100-(Date.now()-this.lastPhoton))));if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');this.lastPhoton=Date.now();const u=new URL('https://photon.komoot.io/api/');u.search=new URLSearchParams({q,lat:String(center.lat),lon:String(center.lng),limit:'8',lang:'de'});const data=await this.json(u.href,{},signal,16000);const items=fromPhoton(data),entry={time:Date.now(),items};this.cache.set(key,entry);this.write('pizzascan-search-'+key,entry);return items;};const promise=this.photonQueue.then(run,run);this.photonQueue=promise.catch(()=>{});return promise;}
 read(k){try{return JSON.parse(this.storage?.getItem(k)||'null');}catch{return null;}}
 write(k,value){try{if(k.startsWith('pizzascan-search-')&&this.storage){const keys=[];for(let i=0;i<this.storage.length;i++){const name=this.storage.key(i);if(name?.startsWith('pizzascan-search-'))keys.push(name);}if(keys.length>70)keys.slice(0,keys.length-60).forEach(key=>this.storage.removeItem(key));}this.storage?.setItem(k,JSON.stringify(value));return true;}catch{return false;}}
 async details(p,{signal,onUpdate,force=false}={}){if(!force&&p.detailsAt&&Date.now()-Date.parse(p.detailsAt)<86400000)return {place:p,cached:true,errors:[]};let result=p,photonDetails={};const errors=[];const accept=change=>{if(signal?.aborted)return;result=merge([result],[{...change,placeId:p.placeId}])[0];onUpdate?.(result);};
 const outcomes=await Promise.allSettled([this.overpass(detailQuery(p.placeId),{signal}).then(r=>{const exact=fromOverpass(r.data.elements,{allowNamed:true}).find(x=>x.placeId===p.placeId);if(exact)accept({...exact,...photonDetails,dataSource:Object.keys(photonDetails).length?'OpenStreetMap · Photon':'OpenStreetMap'});else throw Error('Ort nicht in Kartendaten gefunden');}),this.photon(p.name,p,{signal,force}).then(items=>{const hit=items.find(x=>x.osmId===p.placeId);if(!hit)throw Error('Keine passende Adresszuordnung');photonDetails={address:hit.address||result.address,country:hit.country||result.country,state:hit.state||result.state};accept({...result,...photonDetails,tags:{},dataSource:'OpenStreetMap · Photon'});})]);
 if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');outcomes.forEach(o=>{if(o.status==='rejected')errors.push(o.reason?.message||'Details nicht erreichbar');});if(outcomes.some(o=>o.status==='fulfilled')){result.detailsAt=errors.length?'':new Date().toISOString();onUpdate?.(result);}return {place:result,errors};}
}
return {TYPES,providers,defaults,text,address,normalize,fromOverpass,merge,query,detailQuery,within,rank,suggestions,filter,fromPhoton,features,Service};
});
