/* Location-rating presentation and bounded background loading. All copy is localized. */
(function(root){
  'use strict';
  const langs=['de','en','it','es','fr'];
  const copy={
    shortcut:['Bewertungen','Ratings','Valutazioni','Valoraciones','Notes'],
    apply:['Bewertungsfilter anwenden','Apply rating filter','Applica filtro valutazioni','Aplicar filtro de valoraciones','Appliquer le filtre par note'],
    heading:['Offene Ortsbewertungen','Open place ratings','Valutazioni aperte dei luoghi','Valoraciones abiertas de lugares','Notes ouvertes des lieux'],
    enable:['Offene Bewertungen laden','Load open ratings','Carica valutazioni aperte','Cargar valoraciones abiertas','Charger les notes ouvertes'],
    free:['Kostenlose Daten von Mangrove/Open Reviews. Die Abdeckung ist lückenhaft.','Free data from Mangrove/Open Reviews. Coverage is incomplete.','Dati gratuiti di Mangrove/Open Reviews. La copertura è incompleta.','Datos gratuitos de Mangrove/Open Reviews. La cobertura es incompleta.','Données gratuites de Mangrove/Open Reviews. La couverture est incomplète.'],
    minimum:['Mindestbewertung','Minimum rating','Valutazione minima','Valoración mínima','Note minimale'],
    off:['Aus · alle Bewertungen','Off · all ratings','Disattivato · tutte le valutazioni','Desactivado · todas las valoraciones','Désactivé · toutes les notes'],
    at:['Ab {value} von 5','At least {value} out of 5','Almeno {value} su 5','Al menos {value} de 5','Au moins {value} sur 5'],
    unknownOption:['Orte ohne offene Bewertung trotzdem anzeigen','Also show places without an open rating','Mostra anche luoghi senza valutazioni aperte','Mostrar también lugares sin valoración abierta','Afficher aussi les lieux sans note ouverte'],
    scope:['Der Filter gilt für die angezeigten Mangrove-Mittelwerte in Karte und Liste. Eigene Foto- und Besuchsbewertungen zählen nicht mit.','The filter uses the displayed Mangrove averages on the map and in the list. Your photo and visit ratings are excluded.','Il filtro usa le medie Mangrove visualizzate sulla mappa e nell’elenco. Le tue valutazioni di foto e visite non sono incluse.','El filtro usa los promedios de Mangrove mostrados en el mapa y la lista. Tus valoraciones de fotos y visitas no se incluyen.','Le filtre utilise les moyennes Mangrove affichées sur la carte et dans la liste. Vos notes de photos et de visites ne sont pas incluses.'],
    loading:['Offene Bewertungen werden geladen …','Loading open ratings …','Caricamento delle valutazioni aperte …','Cargando valoraciones abiertas …','Chargement des notes ouvertes …'],
    unloaded:['Offene Bewertung noch nicht geladen','Open rating not loaded yet','Valutazione aperta non ancora caricata','Valoración abierta aún no cargada','Note ouverte pas encore chargée'],
    none:['Keine zugeordnete offene Bewertung','No matching open rating','Nessuna valutazione aperta corrispondente','Sin valoración abierta correspondiente','Aucune note ouverte correspondante'],
    unavailable:['Bewertungsquelle zurzeit nicht erreichbar','Ratings source currently unavailable','Fonte delle valutazioni al momento non disponibile','Fuente de valoraciones no disponible','Source des notes actuellement indisponible'],
    failed:['Nicht alle Bewertungen konnten geladen werden. Gespeicherte Werte bleiben mit Datum sichtbar.','Some ratings could not be loaded. Saved values remain visible with their date.','Non è stato possibile caricare tutte le valutazioni. I valori salvati restano visibili con la data.','No se pudieron cargar todas las valoraciones. Los valores guardados siguen visibles con su fecha.','Certaines notes n’ont pas pu être chargées. Les valeurs enregistrées restent visibles avec leur date.'],
    count:['{count} Bewertungen','{count} ratings','{count} valutazioni','{count} valoraciones','{count} notes'],
    one:['1 Bewertung','1 rating','1 valutazione','1 valoración','1 note'],
    coverage:['Offene Bewertung für {rated} von {total} Orten','Open rating for {rated} of {total} places','Valutazione aperta per {rated} di {total} luoghi','Valoración abierta para {rated} de {total} lugares','Note ouverte pour {rated} lieux sur {total}'],
    hidden:['Orte ohne bekannte offene Bewertung sind ausgeblendet.','Places without a known open rating are hidden.','I luoghi senza valutazioni aperte note sono nascosti.','Los lugares sin valoración abierta conocida están ocultos.','Les lieux sans note ouverte connue sont masqués.'],
    noMatches:['Keine Orte erfüllen den Bewertungsfilter. Es können noch offene Bewertungen fehlen.','No places meet the rating filter. Open ratings may still be missing.','Nessun luogo soddisfa il filtro. Potrebbero mancare valutazioni aperte.','Ningún lugar cumple el filtro. Puede que falten valoraciones abiertas.','Aucun lieu ne satisfait le filtre. Des notes ouvertes peuvent encore manquer.'],
    reset:['Bewertungsfilter ausschalten','Turn off rating filter','Disattiva filtro valutazioni','Desactivar filtro de valoraciones','Désactiver le filtre par note'],
    retry:['Bewertungen aktualisieren','Refresh ratings','Aggiorna valutazioni','Actualizar valoraciones','Actualiser les notes'],
    average:['PizzaScan-Mittelwert aus Mangrove-Bewertungen','PizzaScan average of Mangrove ratings','Media PizzaScan delle valutazioni Mangrove','Promedio de PizzaScan de las valoraciones de Mangrove','Moyenne PizzaScan des notes Mangrove'],
    updated:['Datenstand: {date}','Data retrieved: {date}','Dati aggiornati: {date}','Datos consultados: {date}','Données consultées : {date}'],
    cached:['Gespeicherter Stand','Saved data','Dati salvati','Datos guardados','Données enregistrées'],
    source:['Originalbewertungen bei Mangrove ↗','Original ratings on Mangrove ↗','Valutazioni originali su Mangrove ↗','Valoraciones originales en Mangrove ↗','Notes originales sur Mangrove ↗'],
    calculation:['Quelle & Berechnung','Source & calculation','Fonte e calcolo','Fuente y cálculo','Source et calcul'],
    calculationText:['Quelle: Open Reviews/Mangrove. PizzaScan berechnet einen eigenen Mittelwert: 0–100 Punkte werden auf 1–5 Sterne umgerechnet und auf eine Nachkommastelle gerundet. Dieser angezeigte Wert gilt für den Filter. Pro öffentlicher Bewertungsidentität zählt die jüngste zugeordnete Bewertung.','Source: Open Reviews/Mangrove. PizzaScan calculates its own average: 0–100 points are converted to 1–5 stars and rounded to one decimal. This displayed value is used by the filter. Only the latest matched rating per public reviewer identity counts.','Fonte: Open Reviews/Mangrove. PizzaScan calcola una propria media: 0–100 punti vengono convertiti in 1–5 stelle e arrotondati a un decimale. Il filtro usa questo valore visualizzato. Conta solo l’ultima valutazione associata per identità pubblica del recensore.','Fuente: Open Reviews/Mangrove. PizzaScan calcula su propio promedio: convierte 0–100 puntos en 1–5 estrellas y redondea a un decimal. El filtro usa este valor mostrado. Solo cuenta la última valoración asociada por identidad pública de autor.','Source : Open Reviews/Mangrove. PizzaScan calcule sa propre moyenne : 0–100 points sont convertis en 1–5 étoiles, arrondies à une décimale. Le filtre utilise cette valeur affichée. Seule la dernière note associée par identité publique compte.'],
    verification:['Bewertungen sind Meinungen; ein tatsächlicher Besuch wird von PizzaScan nicht verifiziert. Keine automatische Zusammenfassung fremder Rezensionstexte.','Ratings are opinions; PizzaScan does not verify an actual visit. Third-party review texts are not automatically summarized.','Le valutazioni sono opinioni; PizzaScan non verifica una visita effettiva. Nessun riepilogo automatico dei testi di recensioni altrui.','Las valoraciones son opiniones; PizzaScan no verifica las visitas. No se resumen automáticamente textos de reseñas ajenas.','Les notes sont des opinions ; PizzaScan ne vérifie pas les visites. Aucun résumé automatique des textes d’avis tiers.'],
    portals:['Auf Bewertungsportalen suchen','Search review platforms','Cerca sui portali di recensioni','Buscar en portales de reseñas','Rechercher sur les plateformes d’avis'],
    portalHint:['Öffnet den Anbieter außerhalb der App. Bitte den passenden Standort prüfen. Diese Portalwerte fließen nicht in den Filter ein.','Opens the provider outside the app. Check that the location matches. These platform ratings do not affect the filter.','Apre il fornitore fuori dall’app. Verifica che il luogo corrisponda. Queste valutazioni non incidono sul filtro.','Abre el proveedor fuera de la app. Comprueba que el lugar coincida. Estas valoraciones no afectan al filtro.','Ouvre le fournisseur hors de l’app. Vérifiez le lieu. Ces notes n’influencent pas le filtre.'],
    privacyTitle:['Offene Ortsbewertungen und Bewertungsfilter','Open place ratings and rating filter','Valutazioni aperte e filtro','Valoraciones abiertas y filtro','Notes ouvertes et filtre'],
    privacyText:['Wenn „Offene Bewertungen laden“ eingeschaltet ist, fragt PizzaScan api.mangrove.reviews direkt nach öffentlichen Bewertungen im Bereich geladener Orte ab. Die Open Reviews Association erhält den abgefragten Suchbereich sowie IP-Adresse und technische Verbindungsdaten. Bei standortnaher Suche kann der Bereich Rückschlüsse auf deinen Standort ermöglichen. Deine Fotos, eigenen Bewertungen und Entwürfe werden nicht übertragen. Die Funktion ist in den Einstellungen abschaltbar.','When “Load open ratings” is enabled, PizzaScan queries api.mangrove.reviews directly for public ratings around loaded places. The Open Reviews Association receives the requested area, your IP address and technical connection data. A nearby search may reveal your approximate location. Your photos, personal ratings and drafts are not sent. You can disable the feature in settings.','Quando “Carica valutazioni aperte” è attivo, PizzaScan interroga direttamente api.mangrove.reviews per valutazioni pubbliche nei dintorni dei luoghi caricati. La Open Reviews Association riceve l’area richiesta, l’indirizzo IP e dati tecnici di connessione. Una ricerca nelle vicinanze può rivelare la posizione approssimativa. Foto, valutazioni personali e bozze non vengono inviate. Puoi disattivare la funzione nelle impostazioni.','Con “Cargar valoraciones abiertas” activado, PizzaScan consulta directamente api.mangrove.reviews para obtener valoraciones públicas cerca de los lugares cargados. Open Reviews Association recibe el área solicitada, tu IP y datos técnicos de conexión. Una búsqueda cercana puede revelar tu ubicación aproximada. No se envían fotos, valoraciones personales ni borradores. Puedes desactivar la función en ajustes.','Lorsque « Charger les notes ouvertes » est activé, PizzaScan interroge directement api.mangrove.reviews pour les notes publiques autour des lieux chargés. Open Reviews Association reçoit la zone demandée, votre adresse IP et les données techniques de connexion. Une recherche à proximité peut révéler votre position approximative. Vos photos, notes personnelles et brouillons ne sont pas envoyés. La fonction peut être désactivée dans les réglages.'],
    privacyCache:['Der lokale Bewertungs-Cache enthält nur Zahlen, Ortsbezüge, öffentliche Bewertungskennungen und die zur Vermeidung von Doppelzählungen nötigen öffentlichen Identitäten, keine Rezensionstexte oder Fotos. Er wird bei Bedarf nach 15 Minuten aktualisiert; gespeicherte Ergebnisse werden höchstens sieben Tage genutzt und bei einem Neuabruf ersetzt. Alle Daten lassen sich über Androids App-Speicher löschen. Externe Links zu Google Maps, Tripadvisor und Yelp werden erst nach Antippen geöffnet; dabei gehen die Suchangaben an den gewählten Anbieter.','The local ratings cache contains only numbers, place references, public review identifiers and public identities needed to avoid duplicates, without review texts or photos. It is refreshed as needed after 15 minutes; saved results are used for at most seven days and replaced on refresh. All data can be deleted through Android’s app storage controls. Google Maps, Tripadvisor and Yelp links open only when tapped, sending the search details to the selected provider.','La cache locale contiene solo numeri, riferimenti ai luoghi, identificativi pubblici delle recensioni e identità pubbliche per evitare duplicati, senza testi o foto. Si aggiorna al bisogno dopo 15 minuti; i dati salvati vengono usati per massimo sette giorni e sostituiti all’aggiornamento. Puoi cancellare tutti i dati dalla memoria dell’app in Android. I link Google Maps, Tripadvisor e Yelp si aprono solo al tocco e inviano i dati di ricerca al fornitore scelto.','La caché local solo contiene cifras, referencias a lugares, identificadores públicos de reseñas e identidades públicas para evitar duplicados, sin textos ni fotos. Se actualiza cuando es necesario tras 15 minutos; los resultados se usan como máximo siete días y se sustituyen al actualizar. Puedes borrar todos los datos desde el almacenamiento de la app en Android. Los enlaces de Google Maps, Tripadvisor y Yelp solo se abren al tocarlos, enviando la búsqueda al proveedor elegido.','Le cache local contient uniquement des chiffres, références de lieux, identifiants publics d’avis et identités publiques évitant les doublons, sans textes ni photos. Il est actualisé au besoin après 15 minutes ; les résultats sont utilisés au maximum sept jours et remplacés à l’actualisation. Les données peuvent être supprimées via le stockage de l’app dans Android. Les liens Google Maps, Tripadvisor et Yelp s’ouvrent uniquement au toucher et transmettent la recherche au fournisseur choisi.']
  };
  const lang=()=>document.documentElement.lang?.slice(0,2)||'de';
  const t=(key,values={})=>(copy[key]?.[Math.max(0,langs.indexOf(lang()))]||key).replace(/\{(\w+)\}/g,(_,k)=>String(values[k]??''));
  const esc=root.PizzaCore.esc,number=n=>new Intl.NumberFormat(lang(),{minimumFractionDigits:1,maximumFractionDigits:1}).format(n);
  const service=new PizzaRatings.Service();
  let loading=false,errors=[],revision=0,controller=null,timer=null,activeKey='';
  const known=()=>[...new Map([...mapPool,...saved,...places].map(p=>[p.placeId,p])).values()];
  let frameKnown=[],frameSummaries=new Map();
  function beginRender(){frameKnown=known();frameSummaries=new Map();}
  function summary(p){const key=`${p.placeId}:${p.name}:${p.lat}:${p.lng}`;if(!frameSummaries.has(key))frameSummaries.set(key,service.get(p,frameKnown));return frameSummaries.get(key);}
  const enabled=()=>mapConfig().ratingsEnabled;
  function filterHtml(cfg){return `<fieldset id="ratings-settings" class="rating-filter" translate="no"><legend>${esc(t('heading'))}</legend><label class="check"><input id="ratings-enabled" type="checkbox" ${cfg.ratingsEnabled?'checked':''}><span>${esc(t('enable'))}</span></label><p class="hint">${esc(t('free'))}</p><div class="field"><label for="filter-min-rating">${esc(t('minimum'))}</label><output id="rating-threshold" for="filter-min-rating">${esc(thresholdText(cfg.minRating))}</output><input id="filter-min-rating" type="range" min="0" max="5" step="0.1" value="${cfg.minRating}" ${cfg.ratingsEnabled?'':'disabled'} aria-describedby="rating-filter-help" aria-valuetext="${esc(thresholdText(cfg.minRating))}"></div><label class="check"><input id="filter-unrated" type="checkbox" ${cfg.includeUnrated?'checked':''} ${cfg.ratingsEnabled&&cfg.minRating>0?'':'disabled'}><span>${esc(t('unknownOption'))}</span></label><p class="hint" id="rating-filter-help">${esc(t('scope'))}</p></fieldset>`;}
  const thresholdText=value=>Number(value)>0?t('at',{value:number(Number(value))}):t('off');
  function card(p){
    if(!enabled())return '';
    const info=summary(p);
    const text=info.rating==null?t(info.status==='error'?'unavailable':info.status==='unloaded'?'unloaded':'none'):`★ ${number(info.rating)} / 5 · ${info.count===1?t('one'):t('count',{count:info.count})} · Mangrove${info.stale?' · '+t('cached'):''}`;
    return `<p class="venue-rating ${info.rating==null?'unrated':''}" translate="no" data-rating="${info.rating??''}">${esc(text)}</p>`;
  }
  function portalLinks(p){
    const query=[p.name,p.address||`${p.lat}, ${p.lng}`].join(' ');
    return [ ['Google Maps','https://www.google.com/maps/search/?'+new URLSearchParams({api:'1',query})],['Tripadvisor','https://www.tripadvisor.com/Search?'+new URLSearchParams({q:query})],['Yelp','https://www.yelp.com/search?'+new URLSearchParams({find_desc:p.name,find_loc:p.address||`${p.lat}, ${p.lng}`})] ];
  }
  function details(p){
    const info=summary(p),license=info.license||'CC-BY-4.0';
    const data=enabled()?`<h2>${esc(t('heading'))}</h2>${card(p)}${info.rating!=null?`<p class="hint">${esc(t('average'))}</p>`:''}${loading||info.error||info.status==='error'?`<p class="hint" role="status">${esc(t(loading?'loading':'failed'))}</p>`:''}${info.checkedAt?`<p class="hint">${esc(t('updated',{date:new Date(info.checkedAt).toLocaleString(lang())}))}</p>`:''}<p class="hint">${esc(t('free'))}</p>${(info.subjects||[]).slice(0,8).map(sub=>`<button class="text-button" data-action="venue-link" data-url="${esc(PizzaRatings.sourceUrl(sub))}">${esc(t('source'))}</button>`).join('')}<button class="secondary full" data-action="refresh-ratings" data-id="${esc(p.placeId)}">${esc(t('retry'))}</button><details><summary>${esc(t('calculation'))}</summary><p>${esc(t('calculationText'))}</p><p>${esc(t('verification'))}</p><p><a href="https://open-reviews.net/technology/" target="_blank" rel="noopener noreferrer">Open Reviews / Mangrove</a> · <a href="${PizzaRatings.licenses[license]}" target="_blank" rel="noopener noreferrer">${esc(license)}</a></p></details>`:'';
    return `<section id="venue-ratings" class="venue-ratings" data-place-id="${esc(p.placeId)}" translate="no">${data}<h3>${esc(t('portals'))}</h3><div class="rating-portals">${portalLinks(p).map(([name,url])=>`<button class="secondary" data-action="venue-link" data-url="${esc(url)}">${name} ↗</button>`).join('')}</div><p class="hint">${esc(t('portalHint'))}</p></section>`;
  }
  function paintStatus(){
    const el=document.getElementById('ratings-status'),fs=document.getElementById('fs-rating-filter');if(!el)return;
    const cfg=mapConfig(),list=onlySaved?saved:places;el.hidden=!cfg.ratingsEnabled||!list.length;
    const shortcut=document.getElementById('rating-filter-open');if(shortcut){const active=cfg.ratingsEnabled&&cfg.minRating>0,compact49=!!root.PizzaScanDiscovery49?.build;shortcut.textContent=active?'★ ≥ '+number(cfg.minRating):(compact49?'★ Rating':'★ '+t('shortcut'));shortcut.classList.toggle('active',active);shortcut.setAttribute('aria-pressed',String(active));shortcut.setAttribute('aria-label',t('minimum')+(active?': '+thresholdText(cfg.minRating):''));}
    if(fs){fs.hidden=!cfg.ratingsEnabled||cfg.minRating===0;fs.textContent=cfg.minRating?`★ ≥ ${number(cfg.minRating)} · Mangrove`:'';}
    if(el.hidden)return;
    const rated=list.filter(p=>summary(p).rating!=null).length;
    el.innerHTML=`<a href="https://open-reviews.net/technology/" target="_blank" rel="noopener noreferrer">Mangrove / Open Reviews</a><span>${esc(loading?t('loading'):errors.length?t('failed'):t('coverage',{rated,total:list.length}))}</span>${cfg.minRating>0?`<strong>${esc(thresholdText(cfg.minRating))}</strong>${cfg.includeUnrated?'':`<span>${esc(t('hidden'))}</span>`}<button class="text-button" data-action="clear-rating-filter">${esc(t('reset'))}</button>`:''}${errors.length?`<button class="text-button" data-action="refresh-ratings">${esc(t('retry'))}</button>`:''}`;
  }
  function repaint(){
    if(typeof renderPlaces==='function')renderPlaces();
    const el=document.getElementById('venue-ratings');if(el){const p=known().find(x=>x.placeId===el.dataset.placeId);if(p)el.outerHTML=details(p);}
  }
  function schedule(list,force=false){
    const key=list.map(p=>`${p.placeId}:${p.lat}:${p.lng}`).sort().join('|');
    if(enabled()&&loading&&key===activeKey&&!force)return;
    clearTimeout(timer);
    if(!enabled()){controller?.abort();revision++;loading=false;errors=[];activeKey='';paintStatus();return;}
    if(!list.length){controller?.abort();revision++;loading=false;activeKey='';paintStatus();return;}
    if(!force&&list.every(p=>service.areaFor(p,true)||service.failureFor(p))){controller?.abort();revision++;loading=false;errors=list.some(p=>service.failureFor(p))?['ratings-unavailable']:[];paintStatus();return;}
    controller?.abort();const own=++revision;activeKey=key;loading=true;errors=[];paintStatus();
    timer=setTimeout(async()=>{
      if(own!==revision)return;
      const ctl=controller=new AbortController();
      try{const result=await service.load(list,{signal:ctl.signal,force,onUpdate:()=>{if(own===revision)repaint();}});if(own===revision)errors=result.errors;}
      catch(e){if(own===revision&&!ctl.signal.aborted)errors=[e.message];}
      finally{if(own===revision){loading=false;repaint();}}
    },150);
  }
  function openFilter(){openSheet('rating-filters',t('shortcut'),filterHtml(mapConfig())+`<button id="rating-apply" class="primary full" translate="no" data-action="apply-rating-filter">${esc(t('apply'))}</button>`);}
  function applyFilter(){settings.filters={...mapConfig(),ratingsEnabled:document.getElementById('ratings-enabled').checked,minRating:PizzaRatings.minimum(document.getElementById('filter-min-rating').value),includeUnrated:document.getElementById('filter-unrated').checked};saveSettings();map.closePopup();closeSheet();refreshArea();}
  function refresh(id){const list=id?known().filter(p=>p.placeId===id):onlySaved?saved:places;schedule(list,true);}
  function privacyHtml(){return `<section class="ratings-privacy" translate="no"><h2>${esc(t('privacyTitle'))}</h2><p>${esc(t('privacyText'))}</p><p>${esc(t('privacyCache'))}</p><p><a href="https://mangrove.reviews/terms" target="_blank" rel="noopener noreferrer">Open Reviews / Mangrove</a> · <a href="https://www.tripadvisor.com/pages/privacy.html" target="_blank" rel="noopener noreferrer">Tripadvisor</a> · <a href="https://terms.yelp.com/privacy" target="_blank" rel="noopener noreferrer">Yelp</a></p></section>`;}
  function syncFilterControls(){
    const range=document.getElementById('filter-min-rating'),toggle=document.getElementById('ratings-enabled'),value=document.getElementById('rating-threshold'),unknown=document.getElementById('filter-unrated');
    if(!range||!toggle)return;
    range.disabled=!toggle.checked;
    unknown.disabled=!toggle.checked||Number(range.value)===0;
    const text=thresholdText(range.value);
    if(value)value.textContent=text;
    range.setAttribute('aria-valuetext',text);
  }
  function filterControlEvent(event){if(['filter-min-rating','ratings-enabled'].includes(event.target.id))syncFilterControls();}
  document.addEventListener('input',filterControlEvent);
  document.addEventListener('change',filterControlEvent);
  root.PizzaRatingsUI={t,copy,service,summary,card,details,filterHtml,paintStatus,schedule,refresh,privacyHtml,portalLinks,beginRender,openFilter,applyFilter,
    passes:(p,cfg)=>!cfg.ratingsEnabled||cfg.minRating===0||PizzaRatings.passes(summary(p),cfg.minRating,cfg.includeUnrated),
    get loading(){return loading;},get errors(){return errors;}};
})(globalThis);
