/* PizzaScan in-app release history, download archive and coverage audit. */
'use strict';
(function(root){
 const RELEASE={version:'2.3.23',build:58,next:'Google Play Closed Track',repo:'https://github.com/chekento/Pizzascan',changelog:'https://github.com/chekento/Pizzascan/blob/main/CHANGELOG.md',archive:'https://github.com/chekento/Pizzascan/blob/main/downloads/README.md',apk:'https://raw.githubusercontent.com/chekento/Pizzascan/main/downloads/PizzaScan-2.3.23.apk'};
 const COPY={
  de:{jump:'📝 Versionen',title:'Versionen & Changelog',current:'Aktuelle Direktversion',next:'Als Nächstes',nextText:'Build 58 erweitert die App um automatische Browser-Spracherkennung, vierzehn UI-Sprachen und eine zentrale Übersetzungsschicht für statische und spät erzeugte Inhalte. Die Build-57-Karten-, GPS- und Score-Funktionen bleiben enthalten.',history:'Archivierte APKs',historyText:'2.3.0 bis 2.3.22 bleiben für Regression und Gerätevergleiche im Archiv verfügbar.',changelog:'📝 Changelog öffnen',archive:'📦 Alte Versionen',download:'⬇️ PizzaScan APK',note:'Die Direkt-APK ist vollständig installierbar. Build 58 nutzt den verfügbaren Direct-Release-Schlüssel; ein Update von einer anders signierten Direkt-APK kann eine Neuinstallation erfordern. Lokale Daten vorher sichern.'},
  en:{jump:'📝 Versions',title:'Versions & changelog',current:'Current direct build',next:'Next',nextText:'Build 58 adds automatic browser-language detection, fourteen UI languages and one central translation layer for static and late-generated content. The Build 57 map, GPS and shared-score behaviour remains included.',history:'Archived APKs',historyText:'2.3.0 through 2.3.22 remain available for regression and device comparisons.',changelog:'📝 Open changelog',archive:'📦 Older versions',download:'⬇️ PizzaScan APK',note:'The direct APK is installable. Build 58 uses the available direct-release key; updating from a differently signed direct APK may require reinstalling. Back up local data first.'},
  it:{jump:'📝 Versioni',title:'Versioni e changelog',current:'Build diretto attuale',next:'Prossimo',nextText:'La build 58 aggiunge il rilevamento automatico della lingua del browser e quattordici lingue per tutta l’interfaccia, mantenendo la mappa, il GPS e il punteggio live della build 57.',history:'APK archiviate',historyText:'Le versioni 2.3.0–2.3.22 restano disponibili per regressione e confronti.',changelog:'📝 Apri changelog',archive:'📦 Versioni precedenti',download:'⬇️ APK PizzaScan',note:'L’APK diretto è installabile. La build 58 usa la chiave Direct-Release disponibile; un aggiornamento da un’APK diretta con firma diversa può richiedere una reinstallazione. Salva prima i dati locali.'},
  es:{jump:'📝 Versiones',title:'Versiones y registro de cambios',current:'Build directo actual',next:'Siguiente',nextText:'La build 58 añade detección automática del idioma del navegador y catorce idiomas para toda la interfaz, manteniendo el mapa, el GPS y la puntuación en vivo de la build 57.',history:'APK archivadas',historyText:'Las versiones 2.3.0–2.3.22 siguen disponibles para regresión y comparación.',changelog:'📝 Abrir cambios',archive:'📦 Versiones anteriores',download:'⬇️ APK PizzaScan',note:'El APK directo es instalable. La build 58 usa la clave Direct-Release disponible; actualizar desde un APK directo con otra firma puede requerir reinstalar. Guarda antes los datos locales.'},
  fr:{jump:'📝 Versions',title:'Versions et journal des modifications',current:'Build direct actuel',next:'Prochaine étape',nextText:'La build 58 ajoute la détection automatique de la langue du navigateur et quatorze langues pour toute l’interface, tout en conservant la carte, le GPS et la note en direct de la build 57.',history:'APK archivées',historyText:'Les versions 2.3.0–2.3.22 restent disponibles pour les tests de régression et comparaisons.',changelog:'📝 Ouvrir changelog',archive:'📦 Anciennes versions',download:'⬇️ APK PizzaScan',note:'L’APK direct est installable. La build 58 utilise la clé Direct-Release disponible ; une mise à jour depuis un APK direct signé différemment peut exiger une réinstallation. Sauvegardez les données locales.'}
 };
 const OSM_PROVIDERS=['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter','https://overpass.osm.jp/api/interpreter'];
 const FOOD_AMENITIES='restaurant|fast_food|cafe|food_truck|takeaway|food_court|bar|pub|biergarten';
 const FOOD_SHOPS='bakery|deli|convenience|food';
 const PIZZA_RE=/(pizza|pizzeria|pizzaria|pizzerie|pizze|ピザ|披萨|披薩|بيتزا|пицц)/iu;
 const ITALIAN_RE=/(italian|italiano|italiana|ristorante|trattoria|osteria|italien|italienne|italienisch|итал|意大利)/iu;
 const COVERAGE_TTL=10*60*1000;
 let auditPromise=null,lastAudit={key:'',time:0};
 function lang(){const v=(document.documentElement.lang||localStorage.getItem('pizzascan-language-v1')||'de').toLowerCase().slice(0,2);return COPY[v]?v:'en';}
 function html(code=lang()){const t=COPY[code]||COPY.de;return `<details id="pizzascan-release-info"><summary>${t.title}</summary><div class="release-info-body"><p><strong>${t.current}</strong><br>PizzaScan ${RELEASE.version} · Build ${RELEASE.build}</p><p><strong>${t.next}: ${RELEASE.next}</strong><br>${t.nextText}</p><p><strong>${t.history}</strong><br>${t.historyText}</p><div class="card-actions release-actions"><a class="secondary" href="${RELEASE.changelog}" target="_blank" rel="noopener noreferrer">${t.changelog}</a><a class="secondary" href="${RELEASE.archive}" target="_blank" rel="noopener noreferrer">${t.archive}</a><a class="primary" href="${RELEASE.apk}" target="_blank" rel="noopener noreferrer">${t.download}</a></div><p class="hint">${t.note}</p></div></details>`;}
 function decorate(){const body=document.getElementById('sheet-body');if(!body||!document.getElementById('dark-mode'))return false;const code=lang(),t=COPY[code]||COPY.en,current=`PizzaScan ${RELEASE.version} · Build ${RELEASE.build}`;for(const p of body.querySelectorAll('details p'))if(/PizzaScan 2\.3\.\d+/.test(p.textContent||'')){const next=p.innerHTML.replace(/PizzaScan 2\.3\.\d+(?: · Build \d+)?/g,current);if(next!==p.innerHTML)p.innerHTML=next;}let info=document.getElementById('pizzascan-release-info');if(!info){const holder=document.createElement('div');holder.innerHTML=html(code);info=holder.firstElementChild;const privacy=[...body.querySelectorAll('details')].find(d=>(d.querySelector('summary')?.textContent||'').toLowerCase().includes(code==='de'?'datenschutz':'privacy'));if(privacy)privacy.insertAdjacentElement('beforebegin',info);else body.appendChild(info);}const jumps=body.querySelector('.settings-jumps');if(jumps&&!document.getElementById('jump-release')){const b=document.createElement('button');b.id='jump-release';b.className='secondary';b.textContent=t.jump;b.onclick=()=>info.scrollIntoView({block:'start'});jumps.appendChild(b);}return true;}
 function syncVersion(){if(root.PizzaScan)root.PizzaScan.version=RELEASE.version;const badge=document.querySelector('.brand small');if(badge)badge.textContent=RELEASE.version;}
 function tagText(tags={}){const values=[];for(const [key,value] of Object.entries(tags)){if(!value)continue;if(/^(?:name(?::.*)?|brand|operator|cuisine|speciality|product|products|description(?::.*)?|note(?::.*)?|menu(?::.*)?|website:menu|contact:menu)$/i.test(key))values.push(String(value));}return values.join(' ');}
 function pizzaEvidence(tags={}){return tags['vending:pizza']==='yes'||PIZZA_RE.test(String(tags.vending||''))||PIZZA_RE.test(tagText(tags));}
 function italianEvidence(tags={}){return ITALIAN_RE.test([tags.cuisine,tags.name,tags.brand,tags.operator].filter(Boolean).join(' '));}
 function foodObject(tags={}){const amenity=String(tags.amenity||''),shop=String(tags.shop||'');return new RegExp(`^(?:${FOOD_AMENITIES})$`).test(amenity)||new RegExp(`^(?:${FOOD_SHOPS})$`).test(shop)||String(tags.vending||'').toLowerCase().includes('pizza')||tags['vending:pizza']==='yes';}
 function coverageRelevant(element,{includeItalian=true}={}){const tags=element?.tags||{};return foodObject(tags)&&(pizzaEvidence(tags)||(includeItalian&&italianEvidence(tags)));}
 function coverageQuery(area){return `[out:json][timeout:60];(`+`nwr["amenity"~"${FOOD_AMENITIES}"]["name"](${area});`+`nwr["shop"~"${FOOD_SHOPS}"]["name"](${area});`+`nwr["vending"~"pizza",i](${area});nwr["vending:pizza"="yes"](${area});`+`);out body center;`;}
 function currentArea(){try{if(root.PizzaScanGlobalFresh)return null;}catch{}let cfg={},center=null,bounds=null,zoom=0;try{cfg=typeof mapConfig==='function'?mapConfig():root.mapConfig?.()||{};}catch{}try{center=typeof mapCenter==='function'?mapCenter():null;}catch{}try{bounds=typeof boundsObject==='function'?boundsObject():null;}catch{}try{zoom=typeof map!=='undefined'&&map?.getZoom?map.getZoom():0;}catch{}if(!center||!Number.isFinite(Number(center.lat))||!Number.isFinite(Number(center.lng))||zoom<10)return null;const radius=Number(cfg.radius)||0;let area,key;if(radius>0){const r=Math.round(Math.max(.5,Math.min(10,radius))*1000);area=`around:${r},${Number(center.lat)},${Number(center.lng)}`;key=`r:${r}:${Number(center.lat).toFixed(3)}:${Number(center.lng).toFixed(3)}`;}else if(bounds&&['south','west','north','east'].every(k=>Number.isFinite(Number(bounds[k])))){area=[bounds.south,bounds.west,bounds.north,bounds.east].join(',');key=`b:${[bounds.south,bounds.west,bounds.north,bounds.east].map(n=>Number(n).toFixed(3)).join(':')}`;}else return null;return {area,key,includeItalian:cfg.includeItalian!==false};}
 function classify(place){const tags=place?.tags||{},a=String(tags.amenity||'');if(String(tags.vending||'').toLowerCase().includes('pizza')||tags['vending:pizza']==='yes')return 'vending_pizza';if(a==='cafe')return 'cafe';if(a==='fast_food'||a==='takeaway')return 'fast_food';if(a==='food_truck')return 'food_truck';if(pizzaEvidence(tags)&&a==='restaurant')return 'pizzeria';return place.type||'other';}
 function normalizeCoverage(elements=[],includeItalian=true){const P=root.PizzaPlaces;if(!P?.normalize)return[];const out=[];for(const element of elements){if(!coverageRelevant(element,{includeItalian}))continue;let place;try{place=P.normalize(element,{allowNamed:true});}catch{}if(!place)continue;const pizza=pizzaEvidence(place.tags||element.tags||{});place={...place,type:classify(place),pizzaEvidence:pizza?'confirmed':place.pizzaEvidence||'possible',pizzaEvidenceSource:pizza?'osm-complete-audit':place.pizzaEvidenceSource||'osm-italian-candidate',dataSource:'OpenStreetMap'};out.push(place);}return P.merge?P.merge([],out):out;}
 async function fetchCoverage(state,signal){let lastError=null;for(const endpoint of OSM_PROVIDERS){if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');try{const data=await placeService.json(endpoint,{method:'POST',body:new URLSearchParams({data:coverageQuery(state.area)})},signal,60000);if(!Array.isArray(data?.elements)||data.remark)throw Error(data?.remark||'Unvollständige OpenStreetMap-Antwort');return {elements:data.elements,source:new URL(endpoint).hostname};}catch(error){lastError=error;if(signal?.aborted)throw error;}}throw lastError||Error('OpenStreetMap-Vollständigkeitsprüfung nicht erreichbar');}
 async function auditCoverage({force=false,signal}={}){const state=currentArea();if(!state)return {skipped:true,reason:'no-local-area'};if(!force&&state.key===lastAudit.key&&Date.now()-lastAudit.time<COVERAGE_TTL)return {skipped:true,reason:'fresh-audit'};if(auditPromise)return auditPromise;auditPromise=(async()=>{const result=await fetchCoverage(state,signal),extra=normalizeCoverage(result.elements,state.includeItalian);let before=0,after=0;try{before=Array.isArray(mapPool)?mapPool.length:0;if(typeof PlaceData!=='undefined'&&Array.isArray(mapPool))mapPool=PlaceData.merge(mapPool,extra);after=Array.isArray(mapPool)?mapPool.length:before;if(typeof refreshArea==='function')refreshArea();if(typeof storeMapCache==='function')storeMapCache();if(typeof mapSource!=='undefined'&&result.source&&!String(mapSource||'').includes(result.source))mapSource=[mapSource,result.source+' coverage'].filter(Boolean).join(' · ');}catch{}lastAudit={key:state.key,time:Date.now()};return {source:result.source,candidates:result.elements.length,relevant:extra.length,added:Math.max(0,after-before)};})().finally(()=>{auditPromise=null;});return auditPromise;}
 function externalCoverageLinks(place){if(!place||!Number.isFinite(Number(place.lat))||!Number.isFinite(Number(place.lng)))return'';const q=encodeURIComponent(`${place.name||'Pizza'} ${place.address||''}`.trim()),lat=Number(place.lat),lng=Number(place.lng),google=`https://www.google.com/maps/search/?api=1&query=${q}`,microsoft=`https://www.bing.com/maps?q=${q}&cp=${lat}~${lng}&lvl=17`;return `<section class="external-map-check"><h2>Coverage Cross-Check</h2><p class="hint">OpenStreetMap ist der primäre PizzaScan-Datenindex. Google Maps und Microsoft Maps werden als externe Gegenprüfung geöffnet; deren POI-Daten werden wegen Anbieter-Lizenzbedingungen nicht in die OSM-Datenbank kopiert.</p><div class="card-actions"><a class="secondary" href="${google}" target="_blank" rel="noopener noreferrer">Google Maps prüfen ↗</a><a class="secondary" href="${microsoft}" target="_blank" rel="noopener noreferrer">Microsoft Maps prüfen ↗</a></div></section>`;}
 function installCoverage(){try{const smart=root.PizzaSmartDiscovery;if(smart){smart.coverageMode='osm-complete-audit';smart.coverageProviders=OSM_PROVIDERS.slice();smart.coverageNote='Google/Microsoft external cross-check only; no licensed POI commingling.';}}catch{}if(typeof root.detailsHtml==='function'&&!root.detailsHtml.__coverageAudit){const old=root.detailsHtml;const wrapped=function(place){return old.apply(this,arguments)+externalCoverageLinks(place);};wrapped.__coverageAudit=true;wrapped.__inner=old;root.detailsHtml=wrapped;}if(typeof root.loadPlaces==='function'&&!root.loadPlaces.__coverageAudit){const old=root.loadPlaces;const wrapped=async function(options={}){const result=await old.apply(this,arguments);try{if(root.navigator?.onLine!==false){if(options.force||options.complete)await auditCoverage({force:true,signal:options.signal});else auditCoverage({force:false,signal:options.signal}).catch(()=>{});}}catch(error){try{placeService.lastErrors=[...(placeService.lastErrors||[]),{source:'OSM coverage audit',message:error.message||String(error)}];}catch{}}return result;};wrapped.__coverageAudit=true;wrapped.__inner=old;root.loadPlaces=wrapped;}root.PizzaCoverageAudit={audit:auditCoverage,currentArea,query:coverageQuery,pizzaEvidence,italianEvidence,coverageRelevant,normalize:normalizeCoverage,providers:OSM_PROVIDERS.slice(),externalCoverageLinks};}
 function install(){syncVersion();installCoverage();const body=document.getElementById('sheet-body');if(!body)return;new MutationObserver(()=>decorate()).observe(body,{childList:true,subtree:true});new MutationObserver(()=>{const info=document.getElementById('pizzascan-release-info');if(info){info.outerHTML=html(lang());decorate();}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});decorate();}
 const api={RELEASE,COPY,OSM_PROVIDERS,FOOD_AMENITIES,FOOD_SHOPS,html,decorate,syncVersion,tagText,pizzaEvidence,italianEvidence,foodObject,coverageRelevant,coverageQuery,normalizeCoverage,externalCoverageLinks,installCoverage,install};root.PizzaReleaseInfo=api;if(typeof module==='object'&&module.exports)module.exports=api;if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();}
})(typeof window!=='undefined'?window:globalThis);
