/* PizzaScan in-app release history and download archive. */
'use strict';
(function(root){
 const RELEASE={version:'2.3.5',build:34,next:'Google Play Closed Track',repo:'https://github.com/chekento/Pizzascan',changelog:'https://github.com/chekento/Pizzascan/blob/main/CHANGELOG.md',archive:'https://github.com/chekento/Pizzascan/blob/main/downloads/README.md',apk:'https://raw.githubusercontent.com/chekento/Pizzascan/main/downloads/PizzaScan-2.3.5.apk'};
 const COPY={
  de:{jump:'📝 Versionen',title:'Versionen & Changelog',current:'Aktuelle Direktversion',next:'Als Nächstes',nextText:'Build 34 stellt die ursprüngliche WebSim-Suchfamilie vollständig wieder her: Pizza/Pizzeria sowie italienische Restaurants über cuisine=italian, Ristorante, Trattoria, Osteria, passende Cafés/Imbisse/Foodtrucks/Takeaways/Pubs/Bars, Bakeshops und Pizzaautomaten. Wenn Photon bei einer gezielten Italiener-Suche die cuisine-Metadaten nicht mitliefert, bleibt der Treffer nun als semantischer Italiener-Kandidat erhalten, ohne künstlich als bestätigte Pizza oder cuisine=italian markiert zu werden. Offensichtliche Gegenkandidaten wie Asia/Sushi/Thai/Steak/Burger werden dabei ausgeschlossen. Normale Restaurants erscheinen sonst nur mit echter Pizza-Evidenz aus Speisekarte/Produktdaten, Beschreibung oder Rezensionen.',history:'Archivierte APKs',historyText:'2.3.0 bis 2.3.4 bleiben für Regression und Gerätevergleiche im Archiv verfügbar.',changelog:'📝 Changelog öffnen',archive:'📦 Alte Versionen',download:'⬇️ PizzaScan APK',note:'Die Direkt-APK ist vollständig installierbar. Ein späterer Wechsel auf eine anders signierte Google-Play-Ausgabe kann eine Neuinstallation erfordern; lokale Daten vorher sichern.'},
  en:{jump:'📝 Versions',title:'Versions & changelog',current:'Current direct build',next:'Next',nextText:'Build 34 restores the original WebSim discovery family end to end: pizza/pizzeria plus Italian restaurants through cuisine=italian, ristorante, trattoria, osteria, matching cafés/fast food/food trucks/takeaway/pubs/bars, bakeshops and pizza vending. When Photon omits cuisine metadata for a focused Italian search, the venue is now retained as a semantic Italian candidate without fabricating confirmed pizza or cuisine=italian metadata. Obvious contradictory venues such as Asian/sushi/Thai/steak/burger restaurants are rejected. Generic restaurants otherwise require real pizza evidence from menus, product metadata, descriptions or reviews.',history:'Archived APKs',historyText:'2.3.0 through 2.3.4 remain available for regression and device comparisons.',changelog:'📝 Open changelog',archive:'📦 Older versions',download:'⬇️ PizzaScan APK',note:'The direct APK is fully installable. Moving later to a differently signed Google Play build may require reinstalling; back up local data first.'},
  it:{jump:'📝 Versioni',title:'Versioni e changelog',current:'Build diretto attuale',next:'Prossimo',nextText:'La build 34 ripristina la famiglia WebSim: pizza/pizzeria, ristoranti italiani tramite cuisine=italian, ristorante, trattoria, osteria e locali compatibili. Se Photon omette cuisine durante una ricerca italiana mirata, il locale resta un candidato semantico senza inventare metadati. I locali chiaramente incompatibili vengono esclusi; i ristoranti generici richiedono prove reali di pizza.',history:'APK archiviate',historyText:'Le versioni 2.3.0–2.3.4 restano disponibili per regressione e confronti tra dispositivi.',changelog:'📝 Apri changelog',archive:'📦 Versioni precedenti',download:'⬇️ APK PizzaScan',note:'L’APK diretto è installabile. Il passaggio successivo a una build Google Play firmata diversamente può richiedere una reinstallazione; salva prima i dati locali.'},
  es:{jump:'📝 Versiones',title:'Versiones y registro de cambios',current:'Build directo actual',next:'Siguiente',nextText:'La build 34 restaura la familia WebSim: pizza/pizzería, restaurantes italianos mediante cuisine=italian, ristorante, trattoria, osteria y locales relacionados. Si Photon omite cuisine en una búsqueda italiana dirigida, el local se conserva como candidato semántico sin inventar metadatos. Se excluyen locales claramente incompatibles; los restaurantes genéricos necesitan evidencia real de pizza.',history:'APK archivadas',historyText:'Las versiones 2.3.0–2.3.4 siguen disponibles para regresión y comparación entre dispositivos.',changelog:'📝 Abrir cambios',archive:'📦 Versiones anteriores',download:'⬇️ APK PizzaScan',note:'El APK directo es instalable. Un cambio posterior a una build de Google Play con una firma diferente puede requerir reinstalación; guarda antes los datos locales.'},
  fr:{jump:'📝 Versions',title:'Versions et journal des modifications',current:'Build direct actuel',next:'Prochaine étape',nextText:'La build 34 rétablit la famille WebSim : pizza/pizzeria, restaurants italiens via cuisine=italian, ristorante, trattoria, osteria et établissements associés. Si Photon omet cuisine lors d’une recherche italienne ciblée, le lieu reste un candidat sémantique sans inventer de métadonnées. Les établissements clairement incompatibles sont exclus ; les restaurants génériques nécessitent une preuve réelle de pizza.',history:'APK archivées',historyText:'Les versions 2.3.0–2.3.4 restent disponibles pour la régression et les comparaisons entre appareils.',changelog:'📝 Ouvrir le changelog',archive:'📦 Anciennes versions',download:'⬇️ APK PizzaScan',note:'L’APK direct est installable. Un passage ultérieur à une build Google Play signée différemment peut nécessiter une réinstallation ; sauvegardez d’abord les données locales.'}
 };
 function lang(){const v=(document.documentElement.lang||localStorage.getItem('pizzascan-language-v1')||'de').toLowerCase().slice(0,2);return COPY[v]?v:'de';}
 function html(code=lang()){const t=COPY[code]||COPY.de;return `<details id="pizzascan-release-info"><summary>${t.title}</summary><div class="release-info-body"><p><strong>${t.current}</strong><br>PizzaScan ${RELEASE.version} · Build ${RELEASE.build}</p><p><strong>${t.next}: ${RELEASE.next}</strong><br>${t.nextText}</p><p><strong>${t.history}</strong><br>${t.historyText}</p><div class="card-actions release-actions"><a class="secondary" href="${RELEASE.changelog}" target="_blank" rel="noopener noreferrer">${t.changelog}</a><a class="secondary" href="${RELEASE.archive}" target="_blank" rel="noopener noreferrer">${t.archive}</a><a class="primary" href="${RELEASE.apk}" target="_blank" rel="noopener noreferrer">${t.download}</a></div><p class="hint">${t.note}</p></div></details>`;}
 function decorate(){
  const body=document.getElementById('sheet-body');if(!body||!document.getElementById('dark-mode'))return false;
  const code=lang(),t=COPY[code];
  for(const p of body.querySelectorAll('details p'))if(/PizzaScan 2\.3\.2/.test(p.textContent||''))p.innerHTML=p.innerHTML.replace(/PizzaScan 2\.3\.2/g,`PizzaScan ${RELEASE.version} · Build ${RELEASE.build}`);
  let info=document.getElementById('pizzascan-release-info');
  if(!info){const holder=document.createElement('div');holder.innerHTML=html(code);info=holder.firstElementChild;const privacy=[...body.querySelectorAll('details')].find(d=>(d.querySelector('summary')?.textContent||'').toLowerCase().includes(code==='de'?'datenschutz':'privacy'));if(privacy)privacy.insertAdjacentElement('beforebegin',info);else body.appendChild(info);}
  const jumps=body.querySelector('.settings-jumps');if(jumps&&!document.getElementById('jump-release')){const b=document.createElement('button');b.id='jump-release';b.className='secondary';b.textContent=t.jump;b.onclick=()=>info.scrollIntoView({block:'start'});jumps.appendChild(b);}
  return true;
 }
 function syncVersion(){if(root.PizzaScan)root.PizzaScan.version=RELEASE.version;const badge=document.querySelector('.brand small');if(badge)badge.textContent=RELEASE.version;}
 function install(){syncVersion();const body=document.getElementById('sheet-body');if(!body)return;new MutationObserver(()=>decorate()).observe(body,{childList:true,subtree:true});new MutationObserver(()=>{const info=document.getElementById('pizzascan-release-info');if(info){info.outerHTML=html(lang());decorate();}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});decorate();}
 const api={RELEASE,COPY,html,decorate,syncVersion,install};root.PizzaReleaseInfo=api;if(typeof module==='object'&&module.exports)module.exports=api;if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();}
})(typeof window!=='undefined'?window:globalThis);
