/* PizzaScan in-app release history and download archive. */
'use strict';
(function(root){
 const RELEASE={version:'2.3.4',build:24,next:'Google Play Closed Test',repo:'https://github.com/chekento/Pizzascan',changelog:'https://github.com/chekento/Pizzascan/blob/main/CHANGELOG.md',archive:'https://github.com/chekento/Pizzascan/blob/main/downloads/README.md',apk:'https://raw.githubusercontent.com/chekento/Pizzascan/main/downloads/PizzaScan-2.3.4-Test.apk'};
 const COPY={
  de:{jump:'📝 Versionen',title:'Versionen & Changelog',current:'Aktueller technischer Teststand',next:'Als Nächstes',nextText:'2.3.4 konsolidiert die Such-/POI-Stabilisierung und die neuen Features. Nach erfolgreicher Geräte- und CI-Abnahme folgt das Google-Play-Testpaket.',history:'Erhaltene APKs',historyText:'2.3.0, 2.3.1, 2.3.2 und 2.3.3 bleiben für Regressionstests und Gerätevergleiche im Archiv verfügbar.',changelog:'📝 Changelog öffnen',archive:'📦 Alte Versionen',download:'⬇️ Aktuelle APK',note:'Technische Vorab-APKs sind nicht die spätere geschlossene Google-Play-Testausgabe. Ein Downgrade kann eine Deinstallation erfordern; lokale Daten vorher sichern.'},
  en:{jump:'📝 Versions',title:'Versions & changelog',current:'Current technical test build',next:'Next',nextText:'2.3.4 consolidates the search/POI stabilization and new features. After device and CI acceptance, the Google Play test package follows.',history:'Archived APKs',historyText:'2.3.0, 2.3.1, 2.3.2 and 2.3.3 remain available for regression and device comparison tests.',changelog:'📝 Open changelog',archive:'📦 Older versions',download:'⬇️ Current APK',note:'Technical preview APKs are not the later closed Google Play test release. Downgrading may require uninstalling; back up local data first.'},
  it:{jump:'📝 Versioni',title:'Versioni e changelog',current:'Build tecnico di test attuale',next:'Prossimo',nextText:'La 2.3.4 consolida la stabilizzazione della ricerca/POI e le nuove funzioni. Dopo la validazione su dispositivo e CI seguirà il pacchetto di test Google Play.',history:'APK archiviate',historyText:'Le versioni 2.3.0, 2.3.1, 2.3.2 e 2.3.3 restano disponibili per test di regressione e confronto tra dispositivi.',changelog:'📝 Apri changelog',archive:'📦 Versioni precedenti',download:'⬇️ APK attuale',note:'Le APK tecniche preliminari non sono la futura versione del test chiuso Google Play. Il downgrade può richiedere la disinstallazione; salva prima i dati locali.'},
  es:{jump:'📝 Versiones',title:'Versiones y registro de cambios',current:'Build técnico de prueba actual',next:'Siguiente',nextText:'2.3.4 consolida la estabilización de búsqueda/POI y las nuevas funciones. Tras la validación en dispositivo y CI seguirá el paquete de prueba de Google Play.',history:'APK archivadas',historyText:'2.3.0, 2.3.1, 2.3.2 y 2.3.3 siguen disponibles para pruebas de regresión y comparación entre dispositivos.',changelog:'📝 Abrir cambios',archive:'📦 Versiones anteriores',download:'⬇️ APK actual',note:'Las APK técnicas preliminares no son la futura versión de prueba cerrada de Google Play. Bajar de versión puede requerir desinstalar; guarda antes los datos locales.'},
  fr:{jump:'📝 Versions',title:'Versions et journal des modifications',current:'Build de test technique actuel',next:'Prochaine étape',nextText:'La 2.3.4 consolide la stabilisation de la recherche/POI et les nouvelles fonctions. Après validation sur appareil et CI viendra le paquet de test Google Play.',history:'APK archivées',historyText:'Les versions 2.3.0, 2.3.1, 2.3.2 et 2.3.3 restent disponibles pour les tests de régression et les comparaisons entre appareils.',changelog:'📝 Ouvrir le changelog',archive:'📦 Anciennes versions',download:'⬇️ APK actuelle',note:'Les APK techniques préliminaires ne sont pas la future version du test fermé Google Play. Un retour en arrière peut nécessiter une désinstallation ; sauvegardez d’abord les données locales.'}
 };
 function lang(){const v=(document.documentElement.lang||localStorage.getItem('pizzascan-language-v1')||'de').toLowerCase().slice(0,2);return COPY[v]?v:'de';}
 function html(code=lang()){const t=COPY[code]||COPY.de;return `<details id="pizzascan-release-info"><summary>${t.title}</summary><div class="release-info-body"><p><strong>${t.current}</strong><br>PizzaScan ${RELEASE.version} · Build ${RELEASE.build}</p><p><strong>${t.next}: ${RELEASE.next}</strong><br>${t.nextText}</p><p><strong>${t.history}</strong><br>${t.historyText}</p><div class="card-actions release-actions"><a class="secondary" href="${RELEASE.changelog}" target="_blank" rel="noopener noreferrer">${t.changelog}</a><a class="secondary" href="${RELEASE.archive}" target="_blank" rel="noopener noreferrer">${t.archive}</a><a class="primary" href="${RELEASE.apk}" target="_blank" rel="noopener noreferrer">${t.download}</a></div><p class="hint">${t.note}</p></div></details>`;}
 function decorate(){
  const body=document.getElementById('sheet-body');if(!body||!document.getElementById('dark-mode'))return false;
  const code=lang(),t=COPY[code];
  for(const p of body.querySelectorAll('details p'))if(/PizzaScan 2\.3\.2/.test(p.textContent||''))p.innerHTML=p.innerHTML.replace(/PizzaScan 2\.3\.2/g,`PizzaScan ${RELEASE.version} · Build ${RELEASE.build}`);
  let info=document.getElementById('pizzascan-release-info');
  if(!info){const holder=document.createElement('div');holder.innerHTML=html(code);info=holder.firstElementChild;const privacy=[...body.querySelectorAll('details')].find(d=>(d.querySelector('summary')?.textContent||'').toLowerCase().includes(code==='de'?'datenschutz':'privacy'));if(privacy)privacy.insertAdjacentElement('beforebegin',info);else body.appendChild(info);}
  const jumps=body.querySelector('.settings-jumps');if(jumps&&!document.getElementById('jump-release')){const b=document.createElement('button');b.id='jump-release';b.className='secondary';b.textContent=t.jump;b.onclick=()=>info.scrollIntoView({block:'start'});jumps.appendChild(b);}
  return true;
 }
 function install(){const body=document.getElementById('sheet-body');if(!body)return;new MutationObserver(()=>decorate()).observe(body,{childList:true,subtree:true});new MutationObserver(()=>{const info=document.getElementById('pizzascan-release-info');if(info){info.outerHTML=html(lang());decorate();}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});decorate();}
 const api={RELEASE,COPY,html,decorate,install};root.PizzaReleaseInfo=api;if(typeof module==='object'&&module.exports)module.exports=api;if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();}
})(typeof window!=='undefined'?window:globalThis);
