/* PizzaScan 2 — packaged UI; photos and inference stay on device. */
'use strict';
const C=PizzaCore,A=PizzaAnalysis,$=id=>document.getElementById(id),esc=C.esc;
const SETTINGS='pizzascan-settings-v2';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
const legacy=read('pizzascan-state-v1',{});
let settings={model:'clip32',dark:!!legacy.dark,welcomed:!!legacy.welcomed,...read(SETTINGS,{})};
delete settings.name; delete settings.blocked;
if(!A.models.some(m=>m.id===settings.model))settings.model='clip32';
let saved=read('pizzascan-saved-v2',legacy.want||[]),reports=[],places=[],selectedPlace=null,photo=null,view='map',onlySaved=false,map,markers,position,db,worker,busy=false,sheetKind='',currentReport=null,mapAbort,searchAbort,queryTimer,lastSearch=0;
const nativePending=new Map();
function saveSettings(){const stored=placeService.write(SETTINGS,settings),model=A.models.find(m=>m.id===settings.model);document.body.classList.toggle('dark',settings.dark);$('active-model').textContent=model.name;$('model-download-hint').textContent=`${model.fullName} · ca. ${model.downloadMB} MB zusätzlicher Erstdownload nach Bestätigung. Danach Fotoanalyse offline, solange die Modelldateien gespeichert bleiben.`;if(!stored&&window.PizzaScan?.ready)toast('Gerätespeicher voll: Einstellungen gelten momentan nur bis zum Neustart.');}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6500);}
function actionError(error){console.error(error);toast(error.message||'Das hat nicht geklappt. Bitte erneut versuchen.');}
async function guarded(fn){try{return await fn();}catch(e){actionError(e);}}
function bridge(type,data={}){if(window.PizzaScanNative){const id=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{nativePending.delete(id);reject(Error('Android hat nicht geantwortet'));},15000);nativePending.set(id,{resolve,reject,timer});window.PizzaScanNative.postMessage(JSON.stringify({type,id,...data}));});}
 if(type==='copy')return navigator.clipboard.writeText(data.text);
 if(type==='open'){window.open(data.url,'_blank','noopener');return Promise.resolve('ok');}
 if(type==='sharePhoto'&&navigator.share){return fetch(data.photo).then(r=>r.blob()).then(b=>navigator.share({text:data.text,files:[new File([b],'pizzascan.jpg',{type:'image/jpeg'})]}));}
 if(type==='save'){const blob=new Blob([data.text],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=data.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);return Promise.resolve('ok');}
 return Promise.reject(Error('Diese Aktion benötigt die Android-App.'));}
window.PizzaScanBridge={reply(payload){const p=nativePending.get(payload.id);if(!p)return;clearTimeout(p.timer);nativePending.delete(payload.id);payload.error?p.reject(Error(payload.error)):p.resolve(payload.value);}};
function database(){return new Promise((resolve,reject)=>{const req=indexedDB.open('pizzascan-photos-v2',1);req.onupgradeneeded=()=>req.result.createObjectStore('reports',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Fotospeicher konnte nicht geöffnet werden'));});}
function transaction(mode,run){return new Promise((resolve,reject)=>{const tx=db.transaction('reports',mode);let result;const req=run(tx.objectStore('reports'));if(req)req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(Error('Speichern fehlgeschlagen. Bitte freien Gerätespeicher prüfen.'));tx.onabort=()=>reject(Error('Speichervorgang abgebrochen'));});}
async function persist(r){await transaction('readwrite',s=>s.put(r));reports=reports.filter(x=>x.id!==r.id);reports.unshift(r);renderHistory();}
function openSheet(kind,title,html){sheetKind=kind;$('sheet-kicker').textContent=title;$('sheet-body').onclick=null;$('sheet-body').innerHTML=html;if(!$('sheet').open)$('sheet').showModal();$('sheet').scrollTop=0;}
function closeSheet(){detailRequest?.abort();$('sheet').close();sheetKind='';}
function navigate(next){closeSheet();if(mapFullscreen)setMapFullscreen(false);view=next;document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===next+'-view'));$('nav-map').classList.toggle('selected',next==='map');$('nav-photo').classList.toggle('selected',next==='photo');if(next==='map')setTimeout(()=>map.invalidateSize(),20);window.scrollTo(0,0);}
function empty(text){return '<div class="empty">'+esc(text)+'</div>';}
function placeById(id){return [...places,...saved,...mapPool,...reports.map(r=>r.place).filter(Boolean),selectedPlace].find(p=>p?.placeId===id);}
async function resizePhoto(input,size=1200,quality=.82){const img=await createImageBitmap(input);if(img.width<32||img.height<32){img.close();throw Error('Bitte ein Foto mit mindestens 32 × 32 Pixeln wählen.');}const factor=Math.min(1,size/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*factor);canvas.height=Math.round(img.height*factor);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);img.close();return canvas.toDataURL('image/jpeg',quality);}
async function choosePhoto(){const file=$('photo-input').files[0];if(!file)return;if(busy)return toast('Bitte laufende Analyse zuerst abbrechen');if(file.size>30*1024*1024)throw Error('Bitte ein Foto unter 30 MB wählen');photo=await resizePhoto(file);$('preview').src=photo;$('preview').hidden=false;$('photo-placeholder').hidden=true;$('analyze').disabled=false;$('photo-input').value='';}
function renderHistory(){reports.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('history-count').textContent=reports.length;$('history').innerHTML=reports.map(r=>`<article class="card"><button class="history-row" data-action="report" data-id="${esc(r.id)}"><img class="history-photo" src="${esc(r.photo)}" alt="Pizzafoto"><span><strong>${esc(r.place?.name||'Deine Pizza')}</strong><small>${new Date(r.createdAt).toLocaleDateString('de-DE')} · ${esc(A.models.find(m=>m.id===r.model)?.name||r.model)}</small></span><span class="score">${r.overall.toFixed(1)}<small>/10</small></span></button></article>`).join('')||empty('Deine erste Fotoanalyse wartet auf dich.');}
function setBusy(state){busy=state;$('analyze').disabled=state||!photo;$('photo-input').disabled=state;$('analysis-progress').hidden=!state;}
function stopWorker(){worker?.terminate();worker=null;setBusy(false);toast('Vorgang abgebrochen. Vollständig geladene Modelldateien bleiben gespeichert.');}
function showModelInfo(){const model=A.models.find(m=>m.id===settings.model);openSheet('model-info','OFFLINE-KI · ERKLÄRUNG & DISCLAIMER',`<h1>Deine KI bleibt bei dir.</h1>${PizzaModelInfo.html(model)}<button id="model-info-close" class="secondary full">Verstanden</button>`);$('model-info-close').onclick=closeSheet;}
function showModelDownload(loadOnly){
 const model=A.models.find(m=>m.id===settings.model);
 openSheet('model-download','VOR DEM MODELL-DOWNLOAD',`<h1>Offline-KI vorbereiten</h1>${PizzaModelInfo.html(model)}<div class="model-download-actions"><p class="hint">Mit „Bestätigen & starten“ erlaubst du den Download dieses Modells und bei Bedarf das spätere Nachladen fehlender Dateien. Vorhandene Dateien werden wiederverwendet.</p><button id="confirm-model-download" class="primary full">Bestätigen & starten · ca. ${model.downloadMB} MB</button><button id="model-download-later" class="secondary full">Später · ohne Download zurück</button></div>`);
 $('model-download-later').onclick=closeSheet;
 $('confirm-model-download').onclick=()=>{if(busy)return toast('Es läuft bereits ein Modellvorgang');if(settings.model!==model.id)return showModelDownload(loadOnly);settings.modelNotices={...settings.modelNotices,[model.id]:PizzaModelInfo.version};saveSettings();closeSheet();runModel(loadOnly,true);};
}
function runModel(loadOnly=false,confirmed=false){if(busy)return toast('Es läuft bereits ein Modellvorgang');if(!loadOnly&&!photo)return;if(!confirmed&&(loadOnly||settings.modelNotices?.[settings.model]!==PizzaModelInfo.version))return showModelDownload(loadOnly);setBusy(true);$('progress-label').textContent='KI wird vorbereitet …';$('progress').removeAttribute('value');if(!worker)worker=new Worker('vendor/ai-worker.js',{type:'module'});const usedPhoto=photo,usedPlace=selectedPlace,model=settings.model;
 worker.onerror=e=>{console.error(e);worker?.terminate();worker=null;setBusy(false);toast('KI konnte nicht starten. Bitte Android System WebView aktualisieren und erneut versuchen.');};worker.onmessage=e=>guarded(async()=>{const d=e.data;if(d.type==='progress'){
 if(d.stage==='download'){$('progress-label').textContent=d.status==='progress'?`${A.models.find(m=>m.id===model).name} · Datei ${Math.round((d.loaded||0)/1000000)} / ${Math.round((d.total||0)/1000000)} MB`:'Modelldateien werden vorbereitet …';if(Number.isFinite(d.progress))$('progress').value=d.progress;}
 else {$('progress-label').textContent=`Fotoanalyse auf deinem Gerät · ${d.done} / 25 Kriterien`;$('progress').value=d.done*4;}}
 if(d.type==='loaded'){settings.cached={...settings.cached,[d.id]:new Date().toISOString()};saveSettings();navigator.storage?.persist?.().catch(()=>{});}
 if(d.type==='ready'){setBusy(false);toast('Modell einsatzbereit. Das Foto kann jetzt offline analysiert werden.');}
 if(d.type==='error'){setBusy(false);toast('Analyse nicht abgeschlossen: '+d.message);}
 if(d.type==='result'){setBusy(false);const r={...d,id:crypto.randomUUID(),model,photo:usedPhoto,place:usedPlace,own:null,notes:'',visited:false};delete r.type;await persist(r);showReport(r.id);}
 });worker.postMessage({type:loadOnly?'load':'analyze',id:model,photo:loadOnly?undefined:usedPhoto});}
function categoryRows(scores){return scores.map((s,i)=>`<div class="metric"><div class="metric-line"><span>${String(i+1).padStart(2,'0')} · ${esc(A.categories[i].name)}</span><strong>${s.score.toFixed(1)}</strong></div><div class="bar"><span style="width:${s.score*10}%"></span></div><small>${esc(A.categories[i].group)} · Textvergleich ${s.match>=.65?'deutlich':s.match>=.42?'moderat':'uneindeutig'} · Referenz ${s.anchor+1}/4</small></div>`).join('');}
function showReport(id){const r=reports.find(x=>x.id===id);if(!r)return;currentReport=r;const model=A.models.find(m=>m.id===r.model);const ownPart=`<div class="field"><label for="report-place">Pizzeria zuordnen</label><select id="report-place"><option value="">Ohne Ortszuordnung</option>${[...new Map([r.place,...places,...saved].filter(Boolean).map(p=>[p.placeId,p])).values()].map(p=>`<option value="${esc(p.placeId)}" ${r.place?.placeId===p.placeId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><p class="hint">Ort fehlt? Schließe die Details, suche ihn auf der Karte und öffne diese Analyse erneut.</p><div class="field"><label for="own-rating">Deine persönliche Bewertung</label><div class="rating-value"><span id="own-value">${(r.own??5).toFixed(1)}</span><small> / 10</small></div><input id="own-rating" type="range" min="0.1" max="10" step="0.1" value="${r.own??5}"></div><div class="field"><label for="own-notes">Was hast du selbst erlebt?</label><textarea id="own-notes" maxlength="1500" placeholder="Zum Beispiel Geschmack, Service oder was dir gefallen hat …">${esc(r.notes)}</textarea></div><label class="check"><input id="visited" type="checkbox" ${r.visited?'checked':''}><span>Ich habe diese Pizza selbst probiert. Bewertung und Angaben entsprechen meiner Erfahrung.</span></label><button id="save-own" class="primary full">Eigene Bewertung speichern</button><div class="card-actions"><button id="review-draft" class="secondary" ${r.own===null||!r.visited||!r.place?'disabled':''}>Google-Maps-Entwurf ↗</button><button id="export-review" class="text-button">JSON exportieren</button><button id="delete-review" class="text-button danger">Lokal löschen</button></div><p class="hint">Zuerst Pizzeria, eigene Bewertung und Besuchsbestätigung speichern. Es wird nichts automatisch veröffentlicht.</p>`;
 openSheet('detail','DEINE FOTOBEWERTUNG',`<h1>${esc(r.place?.name||'Deine Pizza im Detail')}</h1>${r.photo?`<img class="detail-photo" src="${esc(r.photo)}" alt="Analysiertes Pizzafoto">`:''}<div class="score-hero"><span class="score">${r.overall.toFixed(1)}</span><span><strong>KI-Fotoindex / 10</strong><small>${esc(model?.name)} · ${new Date(r.createdAt).toLocaleDateString('de-DE')}</small><small>25 Kriterien · 100 simulierte Profile</small></span></div><p class="notice">Experimenteller Bild-Text-Vergleich. Keine Geschmacksprobe und keine 100 unabhängigen Gutachten. Stil und Fotoqualität beeinflussen die Werte.</p><div class="tabs"><button class="active" id="criteria-tab">25 Kriterien</button><button id="experts-tab">100 Perspektiven</button></div><div id="criteria-panel">${categoryRows(r.scores)}</div><div id="experts-panel" hidden><p class="hint">Jedes Profil gewichtet dieselben 25 KI-Fotowerte anders. „Streng“ verschiebt Werte um −0,6, „großzügig“ um +0,4. Dies sind simulierte Bewertungsraster, keine echten Experten.</p><label for="expert-select">Bewertungsprofil auswählen</label><select id="expert-select">${A.profiles(r.scores).map(p=>`<option value="${p.id}">${String(p.id).padStart(3,'0')} · ${esc(p.name)} · ${p.score.toFixed(1)}</option>`).join('')}</select><div id="expert-detail"></div></div><details><summary>So entsteht die Bewertung</summary><p>Das gewählte lokale Modell vergleicht dein Foto mit vier englischen Bildbeschreibungen je Kategorie. Die relativen Ähnlichkeiten ergeben einen unkalibrierten Index von 0,1 bis 10,0. Nachkommastellen bedeuten keine wissenschaftliche Genauigkeit. „Textvergleich“ beschreibt nur die Trennung dieser Referenzen.</p><p>100 Profile kombinieren zehn Fachperspektiven mit zehn Schwerpunkten. Du siehst jeden Einzelwert und sein Gewicht. Der Gesamtindex ist ihr Mittelwert. Geschmack, Geruch, Temperatur und Lebensmittelsicherheit sind aus einem Foto nicht zuverlässig messbar.</p><p>Bei Käse- oder Saucen-freien Pizzen passen manche Kriterien nicht. Niedrige Werte können auch am Pizzastil oder fehlender Sicht liegen; sie sind kein Qualitätsnachweis.</p><p>Modell: ${esc(model?.repo)} · Methode ${A.method}. <a href="https://huggingface.co/${esc(model?.repo)}" target="_blank" rel="noopener">Modellkarte ↗</a></p></details><hr>${ownPart}`);renderExpert();
 $('criteria-tab').onclick=()=>switchDetails(false);$('experts-tab').onclick=()=>switchDetails(true);$('expert-select').onchange=renderExpert;
 $('own-rating').oninput=()=>$('own-value').textContent=Number($('own-rating').value).toFixed(1);$('save-own').onclick=()=>guarded(async()=>{const own=Number($('own-rating').value);A.stars(own);r.own=own;r.notes=$('own-notes').value.trim();r.visited=$('visited').checked;r.place=placeById($('report-place').value)||null;await persist(r);showReport(r.id);toast('Deine Bewertung ist gespeichert');});$('review-draft').onclick=()=>showDraft(r);$('export-review').onclick=()=>guarded(()=>bridge('save',{name:'PizzaScan-'+r.id+'.json',text:JSON.stringify({...r,profiles:A.profiles(r.scores)},null,2)}));$('delete-review').onclick=()=>guarded(async()=>{if(!confirm('Diese Fotoanalyse mit deiner gespeicherten Bewertung auf dem Gerät löschen?'))return;await transaction('readwrite',s=>s.delete(r.id));reports=reports.filter(x=>x.id!==r.id);renderHistory();closeSheet();});}
function switchDetails(expert){$('criteria-panel').hidden=expert;$('experts-panel').hidden=!expert;$('criteria-tab').classList.toggle('active',!expert);$('experts-tab').classList.toggle('active',expert);}
function renderExpert(){const p=A.profiles(currentReport.scores)[Number($('expert-select').value||1)-1];$('expert-detail').innerHTML=`<div class="score-hero"><span class="score">${p.score.toFixed(1)}</span><span><strong>${esc(p.name)}</strong><small>Schwerpunkt ${esc(p.focus)} · Verschiebung ${p.adjustment>0?'+':''}${p.adjustment.toFixed(1)}</small></span></div><div class="table-wrap"><table><thead><tr><th>Kriterium</th><th>Index</th><th>Gewicht</th></tr></thead><tbody>${p.cells.map((v,i)=>`<tr><td>${esc(A.categories[i].name)}</td><td>${v.score.toFixed(1)}</td><td>${v.weight.toFixed(2)}×</td></tr>`).join('')}</tbody></table></div>`;}
function showSettings(section){const previousRadius=mapConfig().radius;openSheet('settings','EINSTELLUNGEN',`<h1>Deine Einstellungen.</h1><div class="settings-jumps"><button id="jump-map" class="secondary">🗺️ Karte</button><button id="jump-ai" class="secondary">🧠 Foto-KI</button></div><div id="map-settings">${filterForm()}</div><hr><h2 id="ki-models">Lokale Foto-KI</h2><p class="lead">Drei kostenlose Bildmodelle. Kein API-Schlüssel, kein KI-Abo, keine Fotoübertragung zur Analyse.</p>${A.models.map(m=>`<label class="model-option"><input type="radio" name="model" value="${m.id}" ${settings.model===m.id?'checked':''}><span><strong>${m.name}</strong><small>${esc(m.note)}</small><small>${settings.cached?.[m.id]?'Bereits geladen · Cache kann vom System bereinigt werden':'Download beim ersten Einsatz'}</small></span></label>`).join('')}<p class="hint">Modelle werden von Hugging Face heruntergeladen. Einmal geladen funktioniert die Analyse offline, solange der Cache vorhanden ist. Keine Modellnutzungsgebühren; eventuelle Mobilfunkkosten bleiben. Die Modelle vergleichen Bild und Text und sind keine spezialisierten Pizza-Gutachter.</p><div id="settings-model-explanation"><details><summary>Offline-Modell: Erklärung & Disclaimer</summary>${PizzaModelInfo.html(A.models.find(m=>m.id===settings.model))}</details></div><button id="download-model" class="primary full">Gewähltes Modell vorbereiten …</button><button id="clear-models" class="text-button">Heruntergeladene Modelle entfernen</button><hr><label class="check"><input id="dark-mode" type="checkbox" ${settings.dark?'checked':''}><span>Dunkles Design</span></label><button id="settings-save" class="secondary full">Einstellungen speichern</button><hr><details><summary>Datenschutz & lokale Daten</summary><p>Fotos und Rezensionsentwürfe bleiben auf deinem Gerät. Kartensuche und Modelldownload verbinden sich mit den jeweils genannten Anbietern. Du kannst einzelne Analysen und Entwürfe direkt in ihren Details löschen. Alle lokalen Daten entfernst du über Android → Apps → PizzaScan → Speicher → Daten löschen. Exportierte Dateien bleiben an ihrem gewählten Speicherort.</p><button id="privacy-open" class="secondary full">Datenschutzerklärung lesen</button></details><details><summary>Version & offene Komponenten</summary><p>PizzaScan 2.2.0 · Android 8 oder neuer. <a href="https://github.com/chekento/Pizzascan">Quellcode und Lizenzen ↗</a></p><p>Leaflet / OpenStreetMap · Transformers.js / ONNX Runtime · CLIP (OpenAI), SigLIP (Google), ONNX-Konvertierungen (Xenova).</p></details>`);
 for(const el of document.querySelectorAll('input[name=model]'))el.onchange=()=>{if(busy){toast('Bitte den laufenden Modellvorgang zuerst beenden');el.checked=false;document.querySelector(`input[value="${settings.model}"]`).checked=true;return;}settings.model=el.value;saveSettings();$('settings-model-explanation').innerHTML=`<details open><summary>Offline-Modell: Erklärung & Disclaimer</summary>${PizzaModelInfo.html(A.models.find(m=>m.id===settings.model))}</details>`;};$('download-model').onclick=()=>{navigate('photo');runModel(true);};$('clear-models').onclick=()=>guarded(async()=>{if(busy)throw Error('Bitte laufenden Vorgang zuerst abbrechen');if(!confirm('Alle heruntergeladenen KI-Modelle entfernen? Fotos bleiben gespeichert.'))return;worker?.terminate();worker=null;const keys=await caches.keys();for(const k of keys)if(k.startsWith('transformers'))await caches.delete(k);settings.cached={};settings.modelNotices={};saveSettings();showSettings();toast('Modellcache entfernt');});$('settings-save').onclick=()=>{readFilterForm();settings.dark=$('dark-mode').checked;saveSettings();toast('Einstellungen gespeichert');closeSheet();refreshArea();if(previousRadius!==mapConfig().radius)loadPlaces({force:true});};$('dark-mode').onchange=()=>{settings.dark=$('dark-mode').checked;saveSettings();};$('privacy-open').onclick=()=>guarded(showPrivacy);$('jump-map').onclick=()=>$('map-settings').scrollIntoView({block:'start'});$('jump-ai').onclick=()=>$('ki-models').scrollIntoView({block:'start'});if(section==='ai')$('ki-models').scrollIntoView({block:'start'});}
async function handleAction(event){const b=event.target.closest('[data-action]');if(!b)return;const id=b.dataset.id;switch(b.dataset.action){case'place':showPlace(id);break;case'save':{const p=placeById(id);if(!p)return;saved=saved.some(x=>x.placeId===id)?saved.filter(x=>x.placeId!==id):[...saved,p];placeService.write('pizzascan-saved-v2',saved);renderPlaces();b.textContent=saved.some(x=>x.placeId===id)?'♥ Gemerkt':'♡ Merken';break;}case'choose':selectedPlace=placeById(id);navigate('photo');toast('Foto wird '+selectedPlace.name+' zugeordnet');break;case'directions':await bridge('open',{url:C.directions([placeById(id)],mapConfig().travelMode,position)});break;case'maps':await bridge('open',{url:A.maps(placeById(id))});break;case'report':showReport(id);break;case'review-builder':showDraft(placeById(id));break;default:return handleMapAction(b);}}
async function init(){saveSettings();db=await database();reports=await transaction('readonly',s=>s.getAll());try{saved=C.importPlaces(saved);}catch{saved=[];}renderHistory();initMap();
 $('nav-map').onclick=()=>navigate('map');$('nav-photo').onclick=()=>navigate('photo');$('settings-open').onclick=showSettings;$('change-model').onclick=()=>showSettings('ai');$('model-info').onclick=showModelInfo;$('welcome-model-info').onclick=showModelInfo;$('welcome-privacy').onclick=()=>guarded(showPrivacy);$('sheet-close').onclick=closeSheet;$('sheet').addEventListener('close',()=>sheetKind='');$('search-form').onsubmit=searchCity;$('gps').onclick=gps;$('map-refresh').onclick=()=>loadPlaces({force:true});$('saved-toggle').onclick=()=>{onlySaved=!onlySaved;renderPlaces();};$('photo-input').onchange=()=>guarded(choosePhoto);$('analyze').onclick=()=>runModel();$('cancel-analysis').onclick=stopWorker;document.addEventListener('click',e=>guarded(()=>handleAction(e)));document.querySelector('.brand').onclick=e=>{e.preventDefault();navigate('map');};$('welcome-start').onclick=()=>{settings.welcomed=true;saveSettings();$('welcome').close();loadPlaces();};$('welcome').addEventListener('cancel',()=>{settings.welcomed=true;saveSettings();loadPlaces();});
 $('welcome-gps').onclick=()=>{settings.welcomed=true;saveSettings();$('welcome').close();gps();};if(!settings.welcomed)$('welcome').showModal();else{loadPlaces();if(settings.gpsOnStart)gps();}window.PizzaScan.ready=true;}
window.PizzaScan={ready:false,back(){if($('sheet').open){closeSheet();return true;}if($('welcome').open){$('welcome-start').click();return true;}if(mapFullscreen){setMapFullscreen(false);return true;}if(view!=='map'){navigate('map');return true;}return false;},diagnostics:()=>({native:!!window.PizzaScanNative,places:places.length,saved:saved.length,reports:reports.length,model:settings.model,busy,view,visiblePlaces:map?visiblePlaces().length:0,markerCount:markers?.getLayers().length||0,mapFullscreen,mapLoading,mapError,mapConfig:mapConfig()})};
init().catch(e=>{console.error(e);$('places').innerHTML=empty('App konnte den lokalen Speicher nicht öffnen. Bitte App neu starten.');toast(e.message);});
